/**************************************************************************************************\
 *** Copyright (c) Robert Bosch Automotive Steering GmbH, Germany
 *** All rights reserved
 ***
 *** Generated by: Raghul Gnanaseelan (MS/EPP10-AS)
 ***
 *** Generated with:
 *** MathWorks MATLAB                            9.9 (R2020b)
 *** dSPACE TargetLink Production Code Generator 5.1p2
 *** AS --- MBSD environment                     R2301-hotfix2
 *** AS --- DataDictionary structure level       5
 *** AS --- MBSD repository
 *** AS ---    sourcecode02.de.bosch.com/projects/MBSD/repos/mbsd/browse?at=537712056067caf70571199527af8b914a901532
 *** AS --- Train repository
 *** AS ---    sourcecode02.de.bosch.com/projects/ASMPAPP/repos/app-train/browse?at=5a2d207c274326c375598a602ae967c9716507f1
\**************************************************************************************************/
/**************************************************************************************************\
 *** 
 *** Simulink model       : ActiveReturn_L_Adapter_sm
 *** TargetLink subsystem : ActiveReturn_L_Adapter_sm/ActiveReturn_L_Adapter
 *** Codefile             : IActiveReturn_L_Adapter_gg.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2023-05-16 10:27:01
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Classic AUTOSAR
 *** AUTOSAR version                          : 4.3.0
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : AvoidPotentiallyUndefinedShiftsBasedOnWorstCaseRange
 s
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : disabled
 *** State activity encoding limit            : 1
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 100
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.1\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.1\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS         CORRESPONDING SIMULINK SUBSYSTEM
 *** SARL1          ActiveReturn_L_Adapter
 *** SARL2          ActiveReturn_L_Adapter/ActRetLAdapter_100msStart
 *** SARL3          ActiveReturn_L_Adapter/ActRetLAdapter_10msEnd
 *** SARL4          ActiveReturn_L_Adapter/ActRetLAdapter_10msStart
 *** SARL5          ActiveReturn_L_Adapter/ActRetLAdapter_DiagData
 *** SARL6          ActiveReturn_L_Adapter/ActRetLAdapter_SetEventEntry
 *** SARL7          ActiveReturn_L_Adapter/Additional_Design_Information
 *** SARL8          ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/SteeringAngleStateMapping
 *** SARL9          ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/SteeringAngleStateMapping/CM_SYM
 ***                BOL_RP_EXACTLY
 *** SARL10         ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/SteeringAngleStateMapping/CM_SYM
 ***                BOL_RP_INITWAIT
 *** SARL11         ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/SteeringAngleStateMapping/CM_SYM
 ***                BOL_RP_INVALID
 *** SARL12         ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/SteeringAngleStateMapping/CM_SYM
 ***                BOL_RP_RAW
 *** SSetEvtHst1    ActiveReturn_L_Adapter/ActRetLAdapter_SetEventEntry/EvtHstI_HlSetEventEntry
 *** SSetEvtHst2    ActiveReturn_L_Adapter/ActRetLAdapter_SetEventEntry/EvtHstI_HlSetEventEntry/TUNN
 ***                EL_SetEvt_s_MonitorStatus
 *** SSetEvtHst3    ActiveReturn_L_Adapter/ActRetLAdapter_SetEventEntry/EvtHstI_HlSetEventEntry/TUNN
 ***                EL_SetEvt_y_MonitorID
 *** SSetEvtHst4    ActiveReturn_L_Adapter/ActRetLAdapter_SetEventEntry/EvtHstI_HlSetEventEntry/TUNN
 ***                EL_SetEvt_y_PrestoreData
 *** SARL13         ActiveReturn_L_Adapter/Additional_Design_Information/Appendix
 *** SARL14         ActiveReturn_L_Adapter/Additional_Design_Information/Calibration_Data
 *** SARL15         ActiveReturn_L_Adapter/Additional_Design_Information/Configuration_Data
 *** SARL16         ActiveReturn_L_Adapter/Additional_Design_Information/Dependencies
 *** SARL17         ActiveReturn_L_Adapter/Additional_Design_Information/Integration_Hints
 *** SARL18         ActiveReturn_L_Adapter/Additional_Design_Information/Interfaces
 *** SARL19         ActiveReturn_L_Adapter/Additional_Design_Information/Internals
 *** SARL20         ActiveReturn_L_Adapter/Additional_Design_Information/Safety_Concept
 *** SARL21         ActiveReturn_L_Adapter/Additional_Design_Information/Short_Description
 *** SARL22         ActiveReturn_L_Adapter/Additional_Design_Information/Calibration_Data/imageFunct
 ***                ionalInterfaces
 *** SARL23         ActiveReturn_L_Adapter/Additional_Design_Information/Integration_Hints/imageFunc
 ***                tionalInterfaces
 *** SARL24         ActiveReturn_L_Adapter/Additional_Design_Information/Interfaces/imageDataInterfa
 ***                ces
 *** SARL25         ActiveReturn_L_Adapter/Additional_Design_Information/Interfaces/imageFunctionalI
 ***                nterfaces
 *** SARL26         ActiveReturn_L_Adapter/Additional_Design_Information/Internals/imageDataInterfac
 ***                es
 *** SARL27         ActiveReturn_L_Adapter/Additional_Design_Information/Internals/imageFunctionalIn
 ***                terfaces
 *** 
 *** SUBSYS         CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE        CORRESPONDING STATEFLOW NODE                    DESCRIPTION
 *** CARL0          ActiveReturn_L_Adapter_sm                       
 *** CARL1          ActiveReturn_L_Adapter/Scheduler                
 *** CARL1                                                          
 *** CARL1                                                          
 *** CARL1                                                          
 *** 
 *** TargetLink version      : 5.1p2 from 24-Jan-2022
 *** Code generator version  : Build Id 5.1.0.30 from 2022-01-24 15:16:38
\**************************************************************************************************/

#ifndef IACTIVERETURN_L_ADAPTER_GG_C
#define IACTIVERETURN_L_ADAPTER_GG_C

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "Rte_ActiveReturn_L_Adapter_Type.h"
#include "Rte_ActiveReturn_L_Adapter.h"
#include "ram_zfls_gg.h"
#include "IRackPositionMain_gg.h"
#include "IEventHistory_hh.h"
#include "IActiveReturn_L_Adapter_gg.h"

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   SLGlobalInit: Default storage class for global variables with initial value | Width: N.A.
\**************************************************************************************************/
struct BS_OP_SARL5I_yActRetI_DiagData yActRetI_DiagData_gds = {
   0, /* m_MotTrqSaturated_s16: 
      Unit: Nm
      LSB: 2^-10 OFF: 0 MIN/MAX: -32 .. 31.9990234375 */
   0, /* m_AbsTorsionBarTorq_u16: 
      Unit: Nm
      LSB: 2^-10 OFF: -0 MIN/MAX: 0 .. 63.9990234375 */
   0, /* v_AbsMaxSafeVehSpd_u16: 
      Unit: km/h
      LSB: 2^-6 OFF: -0 MIN/MAX: 0 .. 1023.984375 */
   0 /* w_AbsSteeringAngle_u16: 
      Unit: °
      LSB: 0.1 OFF: -0 MIN/MAX: 0 .. 6553.5 */
};

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/* start of memory section 'CODE' */
#define ActiveReturn_L_Adapter_START_SEC_CODE
#include "ActiveReturn_L_Adapter_MemMap.h"
/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetLAdapter_100msStart
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturn_L_Adapter_CODE) ActRetLAdapter_100msStart(void)
{
   /* # combined # TargetLink outport: ActiveReturn_L_Adapter/ActRetLAdapter_100msStart/AbsAvgVehSpd
    */
   (void) Rte_Write_PP_VehSpd_AbsAvgVehSpd(GET_vVehSpI_AbsAvgVehSpd_xdu16());
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetLAdapter_10msEnd
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturn_L_Adapter_CODE) ActRetLAdapter_10msEnd(void)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   sint16 Aux_ldS16;

   /* TargetLink inport: ActiveReturn_L_Adapter/ActRetLAdapter_10msEnd/ActvRetMotTrq
      # combined # Signal Conversion: ActiveReturn_L_Adapter/ActRetLAdapter_10msEnd/mActRetI_MotorTo
      rque_sc */
   (void) Rte_Read_RP_ActvRetMotTrq_ActvRetMotTrq(&Aux_ldS16);
   SET_mActRetI_MotorTorque_xds16(Aux_ldS16);
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetLAdapter_10msStart
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturn_L_Adapter_CODE) ActRetLAdapter_10msStart(void)
{
   /* SLLocalInit: Default storage class for local variables with init value | Width: 8 */
   uint8 SARL8_Merge;

   /* # combined # TargetLink outport: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/LoadFacRat */
   (void) Rte_Write_PP_LoadFacRat_LoadFacRat(GET_xCompIncFricI_ActiveRetBoost_xdu16());

   /* # combined # TargetLink outport: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/ActChar */
   (void) Rte_Write_PP_ActChar_ActChar(GET_yApplI_ActCharacteristic_xdu8());

   /* # combined # TargetLink outport: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/ActvRetSpdFac
    */
   (void) Rte_Write_PP_ActvRetFactors_ActvRetSpdFac(GET_xFactMinI_ActiveRetSpeedFactor_xdu16());

   /* # combined # TargetLink outport: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/ActvRetFuncFa
      c */
   (void) Rte_Write_PP_ActvRetFactors_ActvRetFuncFac(GET_xFactMinI_ActiveRetFuncFactor_xdu16());

   /* # combined # TargetLink outport: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/GearSign */
   (void) Rte_Write_PP_GearSign_GearSign(GET_xApplI_GearSign_xds8());
   if (GET_sApplI_SteeringAngleState_xdu8() == RP_RAW) {
      /* Merge: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/SteeringAngleStateMapping/Merge
         update of variable(s) associated with ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/Steer
         ingAngleStateMapping/CM_SYMBOL_RP_RAW/CM_SYMBOL_RP_RAW */
      SARL8_Merge = CM_SYMBOL_RP_RAW;
   }
   else {
      if (GET_sApplI_SteeringAngleState_xdu8() == RP_EXACTLY) {
         /* Merge: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/SteeringAngleStateMapping/Merge
            update of variable(s) associated with ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/St
            eeringAngleStateMapping/CM_SYMBOL_RP_EXACTLY/CM_SYMBOL_RP_EXACTLY */
         SARL8_Merge = CM_SYMBOL_RP_EXACTLY;
      }
      else {
         if (GET_sApplI_SteeringAngleState_xdu8() == RP_INITWAIT) {
            /* Merge: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/SteeringAngleStateMapping/Merg
               e
               update of variable(s) associated with ActiveReturn_L_Adapter/ActRetLAdapter_10msStart
               /SteeringAngleStateMapping/CM_SYMBOL_RP_INITWAIT/CM_SYMBOL_RP_INITWAIT */
            SARL8_Merge = CM_SYMBOL_RP_INITWAIT;
         }
         else {
            /* Merge: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/SteeringAngleStateMapping/Merg
               e
               update of variable(s) associated with ActiveReturn_L_Adapter/ActRetLAdapter_10msStart
               /SteeringAngleStateMapping/CM_SYMBOL_RP_INVALID/CM_SYMBOL_RP_INVALID */
            SARL8_Merge = CM_SYMBOL_RP_INVALID;
         }
      }
   }

   /* # combined # TargetLink outport: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/SteerAngSt */
   (void) Rte_Write_PP_SteerAng_SteerAngSt(SARL8_Merge);

   /* # combined # TargetLink outport: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/SteerAng */
   (void) Rte_Write_PP_SteerAng_SteerAng(GET_wApplI_SteeringAngle_xds16());

   /* # combined # TargetLink outport: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/AbsMaxSafeVeh
      Spd */
   (void) Rte_Write_PP_VehSpd_AbsMaxSafeVehSpd(GET_vVehSpI_AbsMaxSafeVehSpd_xdu16());

   /* # combined # TargetLink outport: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/AbsAvgVehSpd
   */
   (void) Rte_Write_PP_VehSpd_AbsAvgVehSpd(GET_vVehSpI_AbsAvgVehSpd_xdu16());

   /* # combined # TargetLink outport: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/SteerAngSpd
   */
   (void) Rte_Write_PP_SteerAngSpd_SteerAngSpd(GET_vApplI_SteeringAngleSpeed_xds16());

   /* # combined # TargetLink outport: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/TorsBarTrq */
   (void) Rte_Write_PP_TorsBarTrq_TorsBarTrq(GET_mApplI_TorsionBarTorque_xds16());

   /* # combined # TargetLink outport: ActiveReturn_L_Adapter/ActRetLAdapter_10msStart/DrvrTrq */
   (void) Rte_Write_PP_DrvrTrq_DrvrTrq(GET_mApplI_DriverTorque_xds16());
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetLAdapter_DiagData
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturn_L_Adapter_CODE) ActRetLAdapter_DiagData(IDT_ActvRetMotTrqSatn
  ActvRetMotTrqSatn, IDT_ActvRetAbsTorsBarTrqSat ActvRetAbsTorsBarTrqMon, IDT_AbsMaxSafeVehSpd
  ActvRetAbsMaxSafeVehSpdMon, IDT_ActvRetAbsSteerAngSat ActvRetAbsSteerAngMon)
{
   /* BusOutport: ActiveReturn_L_Adapter/ActRetLAdapter_DiagData/yActRetI_DiagData
      # combined # Rescaler: ActiveReturn_L_Adapter/ActRetLAdapter_DiagData/Rescaler3 */
   yActRetI_DiagData_gds.m_MotTrqSaturated_s16 = ActvRetMotTrqSatn;

   /* BusOutport: ActiveReturn_L_Adapter/ActRetLAdapter_DiagData/yActRetI_DiagData
      # combined # Rescaler: ActiveReturn_L_Adapter/ActRetLAdapter_DiagData/Rescaler */
   yActRetI_DiagData_gds.m_AbsTorsionBarTorq_u16 = ActvRetAbsTorsBarTrqMon;

   /* BusOutport: ActiveReturn_L_Adapter/ActRetLAdapter_DiagData/yActRetI_DiagData
      # combined # Rescaler: ActiveReturn_L_Adapter/ActRetLAdapter_DiagData/Rescaler2 */
   yActRetI_DiagData_gds.v_AbsMaxSafeVehSpd_u16 = ActvRetAbsMaxSafeVehSpdMon;

   /* BusOutport: ActiveReturn_L_Adapter/ActRetLAdapter_DiagData/yActRetI_DiagData
      # combined # Rescaler: ActiveReturn_L_Adapter/ActRetLAdapter_DiagData/Rescaler1 */
   yActRetI_DiagData_gds.w_AbsSteeringAngle_u16 = ActvRetAbsSteerAngMon;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetLAdapter_SetEventEntry
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturn_L_Adapter_CODE) ActRetLAdapter_SetEventEntry(IDT_MonStatus MonStatus_Val,
  IDT_MonID MonID_Val, IDT_PrestoreData PrestoreData_Val)
{
   /* call of function: ActiveReturn_L_Adapter/ActRetLAdapter_SetEventEntry/EvtHstI_HlSetEventEntry
   */
   EvtHstI_HlSetEventEntry(MonID_Val, MonStatus_Val, PrestoreData_Val);
}

/* end of memory section 'CODE' */
#define ActiveReturn_L_Adapter_STOP_SEC_CODE
#include "ActiveReturn_L_Adapter_MemMap.h"

/*------------------------------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/
#endif /* IACTIVERETURN_L_ADAPTER_GG_C */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/

