/**************************************************************************************************\
 *** Copyright (c) Robert Bosch Automotive Steering GmbH, Germany
 *** All rights reserved
 ***
 *** Generated by: Rajasridevi Vasupal (RBEI/EPS1)
 ***
 *** Generated with:
 *** MathWorks MATLAB                            8.6 (R2015b)
 *** dSPACE TargetLink Production Code Generator 4.2p4
 *** AS --- MBSD environment                     R1801p1
 *** AS --- DataDictionary structure level       3
 *** AS --- Environment base                     \sgdcc_mbsd\DevEnv\R1801\TargetLink
 *** AS ---    AS_BaseTypeRename.dd              27-Apr-2018 13:34:30
 *** AS ---    AS_FunctionClasses.dd             27-Apr-2018 13:34:30
 *** AS ---    AS_Templates.dd                   27-Apr-2018 13:34:31
 *** AS ---    AS_VariableClasses.dd             27-Apr-2018 13:34:32
 *** AS --- Environment configuration SDK        \sgdcc_eps_sdk\EpsDriveSW\EnvironmentSet\MBSD\R1801\TargetLinkSdkConf
 *** AS ---    asFunctionLib.slx                 05-Aug-2019 16:48:54
 *** AS ---    AS_Defines.dd                     28-Apr-2020 17:09:01
 *** AS ---    AS_DefinesDataFlow.dd             16-Mar-2020 16:39:48
 *** AS ---    AS_GlobalModuleOwn.dd             24-Feb-2020 11:58:51
 *** AS ---    AS_GlobalModules.dd               28-Apr-2020 17:09:02
 *** AS ---    AS_GlobalTypes.dd                 21-Feb-2020 15:18:53
 *** AS --- Environment configuration CPR        \sgdcc_eps_sdk_dev\EpsDriveSW\EnvironmentSet\MBSD\R1801\TargetLinkCprConf
 *** AS ---    AS_ProjModuleOwn.dd               03-May-2018 20:53:34
 *** AS ---    AS_ProjModules.dd                 03-May-2018 20:53:42
 *** AS ---    AS_ProjVariables.dd               03-May-2018 20:53:47
\**************************************************************************************************/
/**************************************************************************************************\
 *** 
 *** Simulink model       : ActiveReturn_sm
 *** TargetLink subsystem : ActiveReturn_sm/ActiveReturn
 *** Codefile             : ActiveReturn_lut_gg.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2020-06-08 15:55:28
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : None
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : disabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : disabled
 *** State activity encoding limit            : 1
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 100
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : O:\sgdcc_mbsd\DevEnv\R1801\TargetLink\Stylesheets\TL
 ***                                            _CSourceCodeSS_AS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** SActRet1                 ActiveReturn
 *** SActRet2                 ActiveReturn/ActRetI_CalcActiveReturnTorque
 *** SActRet3                 ActiveReturn/ActRetI_InterpolCharacteristics
 *** SActRet4                 ActiveReturn/Additional_Design_Information
 *** SActRet5                 ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque
 *** SActRet6                 ActiveReturn/ActRetI_CalcActiveReturnTorque/CalibrationData
 *** SActRet7                 ActiveReturn/ActRetI_CalcActiveReturnTorque/SignalProcessing
 *** SActRet8                 ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Cal
 ***                          culateActiveReturnTorque
 *** SActRet9                 ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Cal
 ***                          culateNominalSteeringAngleSpeed
 *** SActRet10                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Han
 ***                          dleInvalidSignals
 *** SActRet11                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Sat
 ***                          2Range_vActRet_ReturnSpeedDiff
 *** SActRet12                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Cal
 ***                          culateActiveReturnTorque/FiltDriverTorqueDependentFactor
 *** SActRet13                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Cal
 ***                          culateActiveReturnTorque/SymSat_m_MotorTorque3
 *** SActRet14                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Cal
 *** culateActiveReturnTorque/FiltDriverTorqueDependentFactor/PT1Filt_x_Tor
 ***                          queFactorFilt
 *** SActRet15                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Cal
 ***                          culateActiveReturnTorque/SymSat_m_MotorTorque3/lowerLimExceeded
 *** SActRet16                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Cal
 ***                          culateActiveReturnTorque/SymSat_m_MotorTorque3/upperLimExceeded
 *** SActRet17                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Cal
 ***                          culateActiveReturnTorque/SymSat_m_MotorTorque3/withinLimits
 *** SActRet18                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Cal
 ***                          culateNominalSteeringAngleSpeed/FiltSteeringSpeedDependentFactor
 *** SActRet19                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Cal
 ***                          culateNominalSteeringAngleSpeed/InterpolationOverSteeringAngle
 *** SActRet20                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Cal
 *** culateNominalSteeringAngleSpeed/FiltSteeringSpeedDependentFactor/PT1Fi
 ***                          lt_x_SpeedFactorFilt
 *** SActRet21                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Han
 ***                          dleInvalidSignals/RateLim_x_RampFactor
 *** SActRet22                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Sat
 ***                          2Range_vActRet_ReturnSpeedDiff/lowerLimExceeded
 *** SActRet23                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Sat
 ***                          2Range_vActRet_ReturnSpeedDiff/upperLimExceeded
 *** SActRet24                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalcActiveReturnTorque/Sat
 ***                          2Range_vActRet_ReturnSpeedDiff/withinLimits
 *** SActRet25                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalibrationData/xActRet_Re
 ***                          tTorqueFactDepOnDriver_XAU16
 *** SActRet26                ActiveReturn/ActRetI_CalcActiveReturnTorque/CalibrationData/xActRet_St
 ***                          eerSpeedFactDepOnDriver_XAU16
 *** SActRet27                ActiveReturn/ActRetI_CalcActiveReturnTorque/SignalProcessing/Subst_mAp
 ***                          plI_DriverTorque
 *** SActRet28                ActiveReturn/ActRetI_CalcActiveReturnTorque/SignalProcessing/Subst_vAp
 ***                          plI_SteeringAngleSpeed
 *** SActRet29                ActiveReturn/ActRetI_CalcActiveReturnTorque/SignalProcessing/Subst_wAp
 ***                          plI_SteeringAngle
 *** SActRet30                ActiveReturn/ActRetI_CalcActiveReturnTorque/SignalProcessing/Subst_xAp
 ***                          plI_GearSign
 *** SActRet31                ActiveReturn/ActRetI_CalcActiveReturnTorque/SignalProcessing/Subst_xFa
 ***                          ctMinI_ActiveRetFuncFactor
 *** SActRet32                ActiveReturn/ActRetI_CalcActiveReturnTorque/SignalProcessing/Subst_xFa
 ***                          ctMinI_ActiveRetSpeedFactor
 *** SActRet33                ActiveReturn/ActRetI_CalcActiveReturnTorque/SignalProcessing/Valid_vVe
 ***                          hSpI_AbsAvgVehSpd
 *** SActRet34                ActiveReturn/ActRetI_CalcActiveReturnTorque/SignalProcessing/Subst_mAp
 ***                          plI_DriverTorque/Valid_mApplI_DriverTorque
 *** SActRet35                ActiveReturn/ActRetI_CalcActiveReturnTorque/SignalProcessing/Subst_vAp
 ***                          plI_SteeringAngleSpeed/Valid_vApplI_SteeringAngleSpeed
 *** SActRet36                ActiveReturn/ActRetI_CalcActiveReturnTorque/SignalProcessing/Subst_wAp
 ***                          plI_SteeringAngle/Valid_wApplI_SteeringAngle
 *** SActRet37                ActiveReturn/ActRetI_CalcActiveReturnTorque/SignalProcessing/Subst_xAp
 ***                          plI_GearSign/Valid_xApplI_GearSign
 *** SActRet38                ActiveReturn/ActRetI_CalcActiveReturnTorque/SignalProcessing/Subst_xFa
 ***                          ctMinI_ActiveRetFuncFactor/Valid_xFactMinI_ActiveRetFuncFactor
 *** SActRet39                ActiveReturn/ActRetI_CalcActiveReturnTorque/SignalProcessing/Subst_xFa
 ***                          ctMinI_ActiveRetSpeedFactor/Valid_xFactMinI_ActiveRetSpeedFactor
 *** SActRet40                ActiveReturn/ActRetI_InterpolCharacteristics/Subst_vVehSpI_AbsAvgVehSp
 ***                          d
 *** SActRet41                ActiveReturn/ActRetI_InterpolCharacteristics/xActRet_MotorTorqueGain_X
 ***                          AU16
 *** SActRet42                ActiveReturn/ActRetI_InterpolCharacteristics/Subst_vVehSpI_AbsAvgVehSp
 ***                          d/Valid_vVehSpI_AbsAvgVehSpd
 *** SActRet43                ActiveReturn/Additional_Design_Information/Appendix
 *** SActRet44                ActiveReturn/Additional_Design_Information/Calibration_Data
 *** SActRet45                ActiveReturn/Additional_Design_Information/Configuration_Data
 *** SActRet46                ActiveReturn/Additional_Design_Information/Dependencies
 *** SActRet47                ActiveReturn/Additional_Design_Information/Integration_Hints
 *** SActRet48                ActiveReturn/Additional_Design_Information/Interfaces
 *** SActRet49                ActiveReturn/Additional_Design_Information/Internals
 *** SActRet50                ActiveReturn/Additional_Design_Information/Safety_Concept
 *** SActRet51                ActiveReturn/Additional_Design_Information/Short_Description
 *** SActRet52                ActiveReturn/Additional_Design_Information/Calibration_Data/imageFunct
 ***                          ionalInterfaces
 *** SActRet53                ActiveReturn/Additional_Design_Information/Integration_Hints/imageFunc
 ***                          tionalInterfaces
 *** SActRet54                ActiveReturn/Additional_Design_Information/Interfaces/imageDataInterfa
 ***                          ces
 *** SActRet55                ActiveReturn/Additional_Design_Information/Interfaces/imageFunctionalI
 ***                          nterfaces
 *** SActRet56                ActiveReturn/Additional_Design_Information/Internals/imageDataInterfac
 ***                          es
 *** SActRet57                ActiveReturn/Additional_Design_Information/Internals/imageFunctionalIn
 ***                          terfaces
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** CActRet0  ActiveReturn_sm                                        
 *** CActRet1  ActiveReturn/Scheduler                                 
 *** CActRet1                                                         
 *** CActRet1                                                         
 *** CActRet1                                                         
 *** 
 *** TargetLink version      : 4.2p4 from 17-Jan-2019
 *** Code generator version  : Build Id 4.2.0.35 from 2019-01-16 19:04:11

\**************************************************************************************************/

/* The following MISRA warnings are ignored for autogenerated code. */
/* It has been checked that their removal is safe for autocode. */
/* PRQA S 272, 295, 502, 614, 715, 3101, 3102, 3201, 3344 ++ */
/* PRQA S 3358, 3359, 3757, 3784, 4131, 7000, 7001 ++ */

#ifndef ACTIVERETURN_LUT_GG_C
#define ACTIVERETURN_LUT_GG_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "ActiveReturn_lut_gg.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Tab1DIntp2I1T65_ActRet
 *** 
 ***  DESCRIPTION:
 ***      Automatic generated function for Interpolation using PreLook-Up blocks.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const tUI16 *      z_table             pointer to table vector
 ***      tUI8               irx                 1. table input index
 ***      tUI16              fractionX           1. table input fraction
 ***
 ***  RETURNS:
 ***      tUI16
 ***
 ***  SETTINGS:
 ***      Number of table dimensions.........: 1
 ***      Interpolation......................: on
 ***      Distances fit into given bitlengths: no
 ***
\**************************************************************************************************/
tUI16 Tab1DIntp2I1T65_ActRet(const tUI16 * z_table, tUI8 irx, tUI16 fractionX)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   tUI16 Aux_ldu16;
   tUI16 Aux_ldu16_a;

   z_table += irx;
   Aux_ldu16 = *(z_table++);
   if (fractionX != 0) {
      Aux_ldu16_a = *z_table;
      if (Aux_ldu16 <= Aux_ldu16_a) {
         Aux_ldu16 += ((tUI16) ((((tUI32) (tUI16) (Aux_ldu16_a - Aux_ldu16)) * ((tUI32) fractionX))
          >> 16));
      }
      else {
         Aux_ldu16 -= ((tUI16) ((((tUI32) (tUI16) (Aux_ldu16 - Aux_ldu16_a)) * ((tUI32) fractionX))
          >> 16));
      }
   }
   return Aux_ldu16;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Tab2DIntp2I1T33281_ActRet
 *** 
 ***  DESCRIPTION:
 ***      Automatic generated function for Interpolation using PreLook-Up blocks.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const tUI16 *      z_table             pointer to table vector
 ***      tUI8               N                   number of values in y-axis vector
 ***      tUI8               irx                 1. table input index
 ***      tUI16              fractionX           1. table input fraction
 ***      tUI8               iry                 2. table input index
 ***      tUI16              fractionY           2. table input fraction
 ***
 ***  RETURNS:
 ***      tUI16
 ***
 ***  SETTINGS:
 ***      Number of table dimensions.........: 2
 ***      Interpolation......................: on
 ***      Distances fit into given bitlengths: no
 ***
\**************************************************************************************************/
tUI16 Tab2DIntp2I1T33281_ActRet(const tUI16 * z_table, tUI8 N, tUI8 irx, tUI16 fractionX, tUI8 iry,
  tUI16 fractionY)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   tUI16 Aux_ldu16;
   tUI16 Aux_ldu16_a;
   tUI16 Aux_ldu16_b;

   z_table += ((tUI16) (((tUI16) (((tUI16) irx) * ((tUI16) N))) + ((tUI16) iry)));
   Aux_ldu16 = z_table[0];
   if (fractionY == 0) {
      if (fractionX == 0) {
         return Aux_ldu16;
      }
      Aux_ldu16_a = z_table[N];
   }
   else {
      /* 1. Y-Interpolation. */
      Aux_ldu16_b = z_table[1];
      if (Aux_ldu16 <= Aux_ldu16_b) {
         Aux_ldu16 += ((tUI16) ((((tUI32) (tUI16) (Aux_ldu16_b - Aux_ldu16)) * ((tUI32) fractionY))
          >> 16));
      }
      else {
         Aux_ldu16 -= ((tUI16) ((((tUI32) (tUI16) (Aux_ldu16 - Aux_ldu16_b)) * ((tUI32) fractionY))
          >> 16));
      }
      if (fractionX == 0) {
         return Aux_ldu16;
      }
      z_table += N;

      /* 2. Y-Interpolation. */
      Aux_ldu16_a = *(z_table++);

      /* X-Interpolation. */
      Aux_ldu16_b = z_table[0];
      if (Aux_ldu16_a <= Aux_ldu16_b) {
         Aux_ldu16_a += ((tUI16) ((((tUI32) (tUI16) (Aux_ldu16_b - Aux_ldu16_a)) * ((tUI32)
          fractionY)) >> 16));
      }
      else {
         Aux_ldu16_a -= ((tUI16) ((((tUI32) (tUI16) (Aux_ldu16_a - Aux_ldu16_b)) * ((tUI32)
          fractionY)) >> 16));
      }
   }
   if (fractionX != 0) {
      if (Aux_ldu16 <= Aux_ldu16_a) {
         Aux_ldu16 += ((tUI16) ((((tUI32) (tUI16) (Aux_ldu16_a - Aux_ldu16)) * ((tUI32) fractionX))
          >> 16));
      }
      else {
         Aux_ldu16 -= ((tUI16) ((((tUI32) (tUI16) (Aux_ldu16 - Aux_ldu16_a)) * ((tUI32) fractionX))
          >> 16));
      }
   }
   return Aux_ldu16;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      TabIdxS48T513_ActRet
 *** 
 ***  DESCRIPTION:
 ***      Automatic generated function for PreLook-Up Index Search blocks.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const tUI16 *      x_table             pointer to x-axis vector
 ***      tUI8               N                   number of values in x-axis vector
 ***      tUI16              x                   table input
 ***      tUI8 *             irx                 table output
 ***      tUI16 *            fraction            table output
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***      Search algorithm...................: ascending linear search.
 ***      Output configuration...............: output index and fraction, two variables
 ***
\**************************************************************************************************/
void TabIdxS48T513_ActRet(const tUI16 * x_table, tUI8 N, tUI16 x, tUI8 * irx, tUI16 * fraction)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   tUI8 Aux_ldu8;

   /* Saturation. */
   if (x <= *x_table) {
      *irx = 0;
      *fraction = 0;
   }
   else {
      if (x >= x_table[N - 1]) {
         *irx = N - 1;
         *fraction = 0;
      }
      else {
         Aux_ldu8 = 0;

         /* Linear search, start low. */
         x_table++;
         while (x >= *(x_table++)) {
            Aux_ldu8++;
         }
         x_table -= 2;
         *irx = Aux_ldu8;
         *fraction = (tUI16) (((tUI32) (((tUI32) (tUI16) (x - x_table[0])) << 16)) / ((tUI16)
          (x_table[1] - x_table[0])));
      }
   }
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
#endif /* ACTIVERETURN_LUT_GG_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
