/**************************************************************************************************\
 *** Copyright (c) Robert Bosch Automotive Steering GmbH, Germany
 *** All rights reserved
 ***
 *** Generated by: Thachethu Anilkumar Praveen (MS/EPP10-AS)
 ***
 *** Generated with:
 *** MathWorks MATLAB                            9.9 (R2020b)
 *** dSPACE TargetLink Production Code Generator 5.1p2
 *** AS --- MBSD environment                     R2301-hotfix2
 *** AS --- DataDictionary structure level       5
 *** AS --- MBSD repository
 *** AS ---    sourcecode02.de.bosch.com/projects/MBSD/repos/mbsd/browse?at=537712056067caf70571199527af8b914a901532
 *** AS --- Train repository
 *** AS ---    sourcecode02.de.bosch.com/projects/ASMPAPP/repos/app-train/browse?at=af177b3fa99f7fc68559711641311f95b7cad523
\**************************************************************************************************/
/**************************************************************************************************\
 *** 
 *** Simulink model       : ActiveReturn_sm
 *** TargetLink subsystem : ActiveReturn_sm/ActiveReturn
 *** Codefile             : IActRet_Main_gg.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2023-05-24 16:36:02
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Classic AUTOSAR
 *** AUTOSAR version                          : 4.3.0
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : AvoidPotentiallyUndefinedShiftsBasedOnWorstCaseRange
 s
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : disabled
 *** State activity encoding limit            : 1
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 100
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.1\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.1\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS         CORRESPONDING SIMULINK SUBSYSTEM
 *** SActRet1       ActiveReturn
 *** SActRet2       ActiveReturn/ActRetI_CalcActvRetTrq
 *** SActRet3       ActiveReturn/ActRetI_InterpolCharacteristics
 *** SActRet4       ActiveReturn/Additional_Design_Information
 *** SActRet5       ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque
 *** SActRet6       ActiveReturn/ActRetI_CalcActvRetTrq/CalibrationData
 *** SActRet7       ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing
 *** SActRet8       ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturn
 ***                Torque
 *** SActRet9       ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNominalSteer
 ***                ingAngleSpeed
 *** SActRet10      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/HandleInvalidSignals
 *** SActRet11      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/Sat2Range_vActRet_Ret
 ***                urnSpeedDiff
 *** SActRet12      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturn
 ***                Torque/FiltDriverTorqueDependentFactor
 *** SActRet13      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturn
 ***                Torque/SymSat_m_MotorTorque2
 *** SActRet14      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturn
 ***                Torque/SymSat_m_TotalTorque
 *** SActRet15      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturn
 ***                Torque/FiltDriverTorqueDependentFactor/PT1Filt_x_TorqueFactorFilt
 *** SActRet16      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturn
 ***                Torque/SymSat_m_MotorTorque2/lowerLimExceeded
 *** SActRet17      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturn
 ***                Torque/SymSat_m_MotorTorque2/upperLimExceeded
 *** SActRet18      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturn
 ***                Torque/SymSat_m_MotorTorque2/withinLimits
 *** SActRet19      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturn
 ***                Torque/SymSat_m_TotalTorque/lowerLimExceeded
 *** SActRet20      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturn
 ***                Torque/SymSat_m_TotalTorque/upperLimExceeded
 *** SActRet21      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturn
 ***                Torque/SymSat_m_TotalTorque/withinLimits
 *** SActRet22      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNominalSteer
 ***                ingAngleSpeed/FiltSteeringSpeedDependentFactor
 *** SActRet23      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNominalSteer
 ***                ingAngleSpeed/InterpolationOverSteeringAngle
 *** SActRet24      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNominalSteer
 ***                ingAngleSpeed/FiltSteeringSpeedDependentFactor/PT1Filt_x_SpeedFactorFilt
 *** SActRet25      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNominalSteer
 ***                ingAngleSpeed/InterpolationOverSteeringAngle/SSCP_RP_ProvideParameters_Get_vActR
 ***                et_NominalSteeringSpeed_XAU16
 *** SActRet26      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNominalSteer
 ***                ingAngleSpeed/InterpolationOverSteeringAngle/SSCP_RP_ProvideParameters_Get_vActR
 ***                et_NominalSteeringSpeed_XAU16/Src
 *** SActRet27      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNominalSteer
 ***                ingAngleSpeed/InterpolationOverSteeringAngle/SSCP_RP_ProvideParameters_Get_vActR
 ***                et_NominalSteeringSpeed_XAU16/Src/vActRetNominalSteeringSpeed
 *** SActRet28      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/HandleInvalidSignals/
 ***                RateLim_x_RampFactor
 *** SActRet29      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/Sat2Range_vActRet_Ret
 ***                urnSpeedDiff/lowerLimExceeded
 *** SActRet30      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/Sat2Range_vActRet_Ret
 ***                urnSpeedDiff/upperLimExceeded
 *** SActRet31      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/Sat2Range_vActRet_Ret
 ***                urnSpeedDiff/withinLimits
 *** SActRet32      ActiveReturn/ActRetI_CalcActvRetTrq/CalibrationData/SSCP_RP_ActvRetProvParameter
 ***                s_Get_ActvRetRetTrqFactDepOnDrvr
 *** SActRet33      ActiveReturn/ActRetI_CalcActvRetTrq/CalibrationData/SSCP_RP_ActvRetProvParameter
 ***                s_Get_ActvRetSteerSpdFactDepOnDrvr
 *** SActRet34      ActiveReturn/ActRetI_CalcActvRetTrq/CalibrationData/SSCP_RP_ActvRetProvParameter
 ***                s_Get_ActvRetRetTrqFactDepOnDrvr/Src
 *** SActRet35      ActiveReturn/ActRetI_CalcActvRetTrq/CalibrationData/SSCP_RP_ActvRetProvParameter
 ***                s_Get_ActvRetRetTrqFactDepOnDrvr/Src/RetTrqFactDepOnDrvr
 *** SActRet36      ActiveReturn/ActRetI_CalcActvRetTrq/CalibrationData/SSCP_RP_ActvRetProvParameter
 ***                s_Get_ActvRetSteerSpdFactDepOnDrvr/Src
 *** SActRet37      ActiveReturn/ActRetI_CalcActvRetTrq/CalibrationData/SSCP_RP_ActvRetProvParameter
 ***                s_Get_ActvRetSteerSpdFactDepOnDrvr/Src/SteerSpdFactDepOnDrvr
 *** SActRet38      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_ActiveRetFuncFac
 *** SActRet39      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_ActvRetSpdFac
 *** SActRet40      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_DrvrTrq
 *** SActRet41      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_GearSign
 *** SActRet42      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAng
 *** SActRet43      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAngSpd
 *** SActRet44      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_xCompIncFricI_ActiveR
 ***                etBoost
 *** SActRet45      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Valid_AbsAvgVehSpd
 *** SActRet46      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_ActiveRetFuncFac/Vali
 ***                d_ActvRetFuncFac
 *** SActRet47      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_ActvRetSpdFac/Valid_x
 ***                FactMinI_ActiveRetSpeedFactor
 *** SActRet48      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_DrvrTrq/Valid_DrvrTrq
 *** SActRet49      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_GearSign/Valid_xApplI
 ***                _GearSign
 *** SActRet50      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAng/Valid_SteerA
 ***                ng
 *** SActRet51      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAngSpd/Valid_vAp
 ***                plI_SteeringAngleSpeed
 *** SActRet52      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_xCompIncFricI_ActiveR
 ***                etBoost/Valid_xCompIncFricI_ActiveRetBoost
 *** SActRet53      ActiveReturn/ActRetI_InterpolCharacteristics/SSCP_RP_ProvideParameters_Get_xActR
 ***                et_MotorTorqueGain_XAU16
 *** SActRet54      ActiveReturn/ActRetI_InterpolCharacteristics/Subst_AbsAvgVehSpd
 *** SActRet55      ActiveReturn/ActRetI_InterpolCharacteristics/SSCP_RP_ProvideParameters_Get_xActR
 ***                et_MotorTorqueGain_XAU16/Src
 *** SActRet56      ActiveReturn/ActRetI_InterpolCharacteristics/SSCP_RP_ProvideParameters_Get_xActR
 ***                et_MotorTorqueGain_XAU16/Src/INJECT_MotTrqGain
 *** SActRet57      ActiveReturn/ActRetI_InterpolCharacteristics/Subst_AbsAvgVehSpd/Valid_AbsAvgVehS
 ***                pd
 *** SActRet58      ActiveReturn/Additional_Design_Information/Appendix
 *** SActRet59      ActiveReturn/Additional_Design_Information/Calibration_Data
 *** SActRet60      ActiveReturn/Additional_Design_Information/Configuration_Data
 *** SActRet61      ActiveReturn/Additional_Design_Information/Dependencies
 *** SActRet62      ActiveReturn/Additional_Design_Information/Integration_Hints
 *** SActRet63      ActiveReturn/Additional_Design_Information/Interfaces
 *** SActRet64      ActiveReturn/Additional_Design_Information/Internals
 *** SActRet65      ActiveReturn/Additional_Design_Information/Safety_Concept
 *** SActRet66      ActiveReturn/Additional_Design_Information/Short_Description
 *** SActRet67      ActiveReturn/Additional_Design_Information/Calibration_Data/imageFunctionalInter
 ***                faces
 *** SActRet68      ActiveReturn/Additional_Design_Information/Integration_Hints/imageFunctionalInte
 ***                rfaces
 *** SActRet69      ActiveReturn/Additional_Design_Information/Interfaces/imageDataInterfaces
 *** SActRet70      ActiveReturn/Additional_Design_Information/Interfaces/imageFunctionalInterfaces
 *** SActRet71      ActiveReturn/Additional_Design_Information/Internals/imageDataInterfaces
 *** SActRet72      ActiveReturn/Additional_Design_Information/Internals/imageFunctionalInterfaces
 *** 
 *** SUBSYS         CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE        CORRESPONDING STATEFLOW NODE                    DESCRIPTION
 *** CActRet0       ActiveReturn_sm                                 
 *** CActRet1       ActiveReturn/Scheduler                          
 *** CActRet1                                                       
 *** CActRet1                                                       
 *** CActRet1                                                       
 *** 
 *** TargetLink version      : 5.1p2 from 24-Jan-2022
 *** Code generator version  : Build Id 5.1.0.30 from 2022-01-24 15:16:38
\**************************************************************************************************/

#ifndef IACTRET_MAIN_GG_C
#define IACTRET_MAIN_GG_C

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "Rte_ActiveReturn_Type.h"
#include "Rte_ActiveReturn.h"
#include "IActRet_Main_gg.h"

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/* start of memory section 'CODE' */
#define ActiveReturn_START_SEC_CODE
#include "ActiveReturn_MemMap.h"
/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetI_CalcActiveReturnTorque
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturn_CODE) ActRetI_CalcActiveReturnTorque(void)
{
   /* AS_NOPT_LOCAL: local variables which are not optimizable (RAM) | Width: 16 */
   sint16 v_RawNominalSteeringSpeed_ldS16; /* 
      Unit: °/s
      LSB: 2^-3 OFF: -0 MIN/MAX: -4096 .. 4095.875 */

   /* SLLocal: Default storage class for local variables | Width: 32 */
   sint32 ActvRetSpdFacFilt_ldS32; /* LSB: 2^-20 OFF: -0 MIN/MAX: -2048 .. 2047.99999904633 */
   sint32 ActvRetTrqFacFilt_ldS32; /* LSB: 2^-20 OFF: -0 MIN/MAX: -2048 .. 2047.99999904633 */
   sint32 m_MotorTorque2_ldS32; /* 
      Unit: Nm
      LSB: 2^-10 OFF: 0 MIN/MAX: -2097152 .. 2097151.99902344 */
   sint32 m_TotalTorque_ldS32; /* 
      Unit: Nm
      LSB: 2^-10 OFF: 0 MIN/MAX: -2097152 .. 2097151.99902344 */
   sint32 v_Deviation_ldS32; /* LSB: 2^-10 OFF: -0 MIN/MAX: -12000 .. 12000 */
   sint32 v_MaxRetSpeedDiff_ldS32; /* LSB: 2^-10 OFF: -0 MIN/MAX: -2097152 .. 2097151.99902344 */
   sint32 x_RampFactor_changeRate_ldS32; /* LSB: 2^-15 OFF: -0 MIN/MAX: -65536 .. 65535.9999694824
   */
   sint32 x_RampFactor_ldS32; /* LSB: 2^-15 OFF: -0 MIN/MAX: -65536 .. 65535.9999694824 */
   sint32 x_RampFactor_min_ldS32; /* LSB: 2^-15 OFF: -0 MIN/MAX: -65536 .. 65535.9999694824 */

   /* SLLocal: Default storage class for local variables | Width: 16 */
   IDT_AbsAvgVehSpd AbsAvgVehSpd; /* LSB: 2^-6 OFF: 0 MIN/MAX: 0 .. 500 */
   uint16 AbsDrvrTrq_ldU16; /* 
      Unit: Nm
      LSB: 2^-10 OFF: -0 MIN/MAX: 0 .. 63.9990234375 */
   uint16 AbsSteerAng_ldU16; /* 
      Unit: °
      LSB: 0.1 OFF: -0 MIN/MAX: 0 .. 6553.5 */
   IDT_ActvRetFuncFac ActvRetFuncFac; /* LSB: 2^-10 OFF: 0 MIN/MAX: 0 .. 1 */
   IDT_ActvRetSpdFac ActvRetSpdFac; /* LSB: 2^-10 OFF: 0 MIN/MAX: 0 .. 1 */
   IDT_DrvrTrq DrvrTrq; /* LSB: 2^-10 OFF: 0 MIN/MAX: -25 .. 25 */
   uint16 FilFac_Val; /* LSB: 2^-10 OFF: 0 MIN/MAX: 0.01 .. 1 */
   IDT_LoadFacRat LoadFacRat; /* LSB: 2^-10 OFF: 0 MIN/MAX: 0 .. 3 */
   uint16 NomSteerSpd_Val; /* LSB: 2^-3 OFF: 0 MIN/MAX: 0 .. 1500 */
   uint16 RetTrqFactDepOnDrvr_Val; /* LSB: 2^-10 OFF: 0 MIN/MAX: 0 .. 1 */
   IDT_SteerAng SteerAng; /* LSB: 0.1 OFF: 0 MIN/MAX: -1000 .. 1000 */
   IDT_SteerAngSpd SteerAngSpd; /* LSB: 2^-3 OFF: 0 MIN/MAX: -1500 .. 1500 */
   uint16 SteerSpdAmp_Val; /* LSB: 2^-14 OFF: 0 MIN/MAX: 0 .. 0.02 */
   uint16 SteerSpdFactDepOnDrvr_Val; /* LSB: 2^-10 OFF: 0 MIN/MAX: 0 .. 1 */
   uint16 SteerSpdGradAftInvld_Val; /* LSB: 2^-15 OFF: 0 MIN/MAX: 0 .. 1 */
   sint16 m_DriverTorque_ldS16; /* 
      Unit: Nm
      LSB: 2^-10 OFF: -0 MIN/MAX: -32 .. 31.9990234375 */
   sint16 v_SteeringAngleSpeed_ldS16; /* 
      Unit: °/s
      LSB: 2^-3 OFF: -0 MIN/MAX: -4096 .. 4095.875 */
   sint16 w_SteerAng_ldS16; /* LSB: 0.1 OFF: 0 MIN/MAX: -3276.8 .. 3276.7 */
   uint16 x_FctCoFuncFact_ldU16; /* LSB: 2^-10 OFF: -0 MIN/MAX: 0 .. 63.9990234375 */
   uint16 x_FctCoSpeedFact_ldU16; /* LSB: 2^-10 OFF: -0 MIN/MAX: 0 .. 63.9990234375 */
   uint16 x_LoadFactorRatio_ldU16; /* LSB: 2^-10 OFF: -0 MIN/MAX: 0 .. 63.9990234375 */
   uint16 x_TargetRampFactor_ldU16; /* LSB: 2^-15 OFF: -0 MIN/MAX: 0 .. 1.99996948242188 */

   /* SLLocal: Default storage class for local variables | Width: 8 */
   IDT_GearSign GearSign; /* LSB: 2^0 OFF: 0 MIN/MAX: -1 .. 1 */
   uint8 MaxMotTrqAftLoadFac_Val_a; /* LSB: 2^-6 OFF: 0 MIN/MAX: 0 .. 3 */
   uint8 MaxMotTrq_Val_a; /* LSB: 2^-6 OFF: 0 MIN/MAX: 0 .. 3 */
   IDT_SteerAngSt SteerAngSt; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 3 */
   uint8 SteerSpdFact_Val; /* LSB: 2^-7 OFF: 0 MIN/MAX: 0 .. 1.5 */
   boolean f_DriverTorqueIsValid_ldB;
   boolean f_SteeringAngleSpeedIsValid_ldB;
   boolean f_SteeringAngleValidIsValid_ldB;
   IDT_GearSign x_GearSign_ldS8; /* LSB: 2^0 OFF: 0 MIN/MAX: -1 .. 1 */
   sint8 y_SteeringAngleSign_ldS8;

   /* SLLocal: Default storage class for local variables | Width: 32 */
   IDT_ActvRetTrqFacFilt Aux_ldS32;

   /* SLLocalInit: Default storage class for local variables with init value | Width: 32 */
   sint32 v_ReturnSpeedDiff_ldS32; /* LSB: 2^-10 OFF: -0 MIN/MAX: -1500 .. 1500 */

   /* SLLocalInit: Default storage class for local variables with init value | Width: 16 */
   sint16 m_MotorTorque2_ldS16; /* 
      Unit: Nm
      LSB: 2^-10 OFF: 0 MIN/MAX: -32 .. 31.9990234375 */
   sint16 m_TotalTorque_ldS16; /* 
      Unit: Nm
      LSB: 2^-10 OFF: 0 MIN/MAX: -32 .. 31.9990234375 */

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 16
    */
   static uint16 x_RampFactor_z_sdU16 = 32768 /* 1. */; /* LSB: 2^-15 OFF: -0 MIN/MAX: 0 .. 1.999969
   48242188 */

   /* TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/AbsAvgVehSpd */
   (void) Rte_Read_RP_VehSpd_AbsAvgVehSpd(&AbsAvgVehSpd);

   /* TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/RP_DrvrTrq */
   (void) Rte_Read_RP_DrvrTrq_DrvrTrq(&DrvrTrq);

   /* Logical: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_DrvrTrq/Valid_DrvrTrq/Logi
      calOp
      # combined # Relational: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_DrvrTrq/Va
      lid_DrvrTrq/RelationalOp1
      # combined # Relational: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_DrvrTrq/Va
      lid_DrvrTrq/RelationalOp */
   f_DriverTorqueIsValid_ldB = (DrvrTrq <= ADT_DrvrTrq_UpperLimit) && (DrvrTrq >=
    ADT_DrvrTrq_LowerLimit);

   /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_DrvrTrq/Switch
      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_DrvrTrq/Switch: Omitted comparison 
      with constant. */
   if (f_DriverTorqueIsValid_ldB) {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_DrvrTrq/Switch */
      m_DriverTorque_ldS16 = DrvrTrq;
   }
   else {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_DrvrTrq/Switch */
      m_DriverTorque_ldS16 = 0;
   }

   /* Abs: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/AbsSteeringAngle1 */
   if (m_DriverTorque_ldS16 >= 0) {
      AbsDrvrTrq_ldU16 = (uint16) m_DriverTorque_ldS16;
   }
   else {
      AbsDrvrTrq_ldU16 = (uint16) (-m_DriverTorque_ldS16);
   }

   /* call of function: ActiveReturn/ActRetI_CalcActvRetTrq/CalibrationData/SSCP_RP_ActvRetProvParam
      eters_Get_ActvRetRetTrqFactDepOnDrvr */
   (void) Rte_Call_RP_ActvRetProvParameters_Get_ActvRetRetTrqFactDepOnDrvr(&RetTrqFactDepOnDrvr_Val,
    AbsDrvrTrq_ldU16, AbsAvgVehSpd);

   /* TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/FilFac */
   (void) Rte_Call_RP_ActvRetProvParameters_Get_ActvRetFilFac(&FilFac_Val);
   Aux_ldS32 = *(Rte_Pim_PIM_ActvRetTrqFacFilt());

   /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturnTorque
      /FiltDriverTorqueDependentFactor/TorqueFactorFilt
      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturnTorque/FiltDri
      verTorqueDependentFactor/TorqueFactorFilt: Omitted comparison with constant.
      # combined # Relational: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateA
      ctiveReturnTorque/FiltDriverTorqueDependentFactor/RisingEdge2 */
   if (RetTrqFactDepOnDrvr_Val > ((uint16) (sint16) (Aux_ldS32 >> 10))) {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturnTor
         que/FiltDriverTorqueDependentFactor/TorqueFactorFilt
         # combined # Sum: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiv
         eReturnTorque/FiltDriverTorqueDependentFactor/PT1Filt_x_TorqueFactorFilt/FiltSum
         # combined # Product: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateA
         ctiveReturnTorque/FiltDriverTorqueDependentFactor/PT1Filt_x_TorqueFactorFilt/FiltProd
         # combined # Sum: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiv
         eReturnTorque/FiltDriverTorqueDependentFactor/PT1Filt_x_TorqueFactorFilt/FiltDiff */
      ActvRetTrqFacFilt_ldS32 = ((((sint32) RetTrqFactDepOnDrvr_Val) - ((sint32) (Aux_ldS32 >> 10)))
       * ((sint32) FilFac_Val)) + Aux_ldS32;
   }
   else {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturnTor
         que/FiltDriverTorqueDependentFactor/TorqueFactorFilt */
      ActvRetTrqFacFilt_ldS32 = (sint32) (((uint32) RetTrqFactDepOnDrvr_Val) << 10);
   }

   /* TargetLink outport: ActiveReturn/ActRetI_CalcActvRetTrq/ActvRetTrqFacFilt */
   Rte_IrvWrite_ActRetI_CalcActvRetTrq_IRV_ActvRetTrqFacFilt(ActvRetTrqFacFilt_ldS32);

   /* TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/MaxMotTrqAftLoadFac */
   (void)
    Rte_Call_RP_ActvRetProvParameters_Get_ActvRetMaxMotTrqAftLoadFac(&MaxMotTrqAftLoadFac_Val_a);

   /* TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/MaxMotTrq */
   (void) Rte_Call_RP_ActvRetProvParameters_Get_ActvRetMaxMotTrq(&MaxMotTrq_Val_a);

   /* Rescaler: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/Sat2Range_vActRet_ReturnS
      peedDiff/Rescaler */
   v_MaxRetSpeedDiff_ldS32 = ((sint32) ADT_ActvRetRetSpdDiff_UpperLimit) * 128;

   /* call of function: ActiveReturn/ActRetI_CalcActvRetTrq/CalibrationData/SSCP_RP_ActvRetProvParam
      eters_Get_ActvRetSteerSpdFactDepOnDrvr */
   (void)
    Rte_Call_RP_ActvRetProvParameters_Get_ActvRetSteerSpdFactDepOnDrvr(&SteerSpdFactDepOnDrvr_Val,
    AbsDrvrTrq_ldU16, AbsAvgVehSpd);
   Aux_ldS32 = *(Rte_Pim_PIM_ActvRetSpdFacFilt());

   /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNominalSteeringAng
      leSpeed/FiltSteeringSpeedDependentFactor/SpeedFactorFilt
      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNominalSteeringAngleSpeed/
      FiltSteeringSpeedDependentFactor/SpeedFactorFilt: Omitted comparison with constant.
      # combined # Relational: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateN
      ominalSteeringAngleSpeed/FiltSteeringSpeedDependentFactor/RisingEdge1 */
   if (SteerSpdFactDepOnDrvr_Val > ((uint16) (sint16) (Aux_ldS32 >> 10))) {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNominalSteering
         AngleSpeed/FiltSteeringSpeedDependentFactor/SpeedFactorFilt
         # combined # Sum: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNomin
         alSteeringAngleSpeed/FiltSteeringSpeedDependentFactor/PT1Filt_x_SpeedFactorFilt/FiltSum
         # combined # Product: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateN
         ominalSteeringAngleSpeed/FiltSteeringSpeedDependentFactor/PT1Filt_x_SpeedFactorFilt/FiltPro
         d
         # combined # Sum: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNomin
         alSteeringAngleSpeed/FiltSteeringSpeedDependentFactor/PT1Filt_x_SpeedFactorFilt/FiltDiff */
      ActvRetSpdFacFilt_ldS32 = ((((sint32) SteerSpdFactDepOnDrvr_Val) - ((sint32) (Aux_ldS32 >>
       10))) * ((sint32) FilFac_Val)) + Aux_ldS32;
   }
   else {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNominalSteering
         AngleSpeed/FiltSteeringSpeedDependentFactor/SpeedFactorFilt */
      ActvRetSpdFacFilt_ldS32 = (sint32) (((uint32) SteerSpdFactDepOnDrvr_Val) << 10);
   }

   /* TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/SteerSpdFact */
   (void) Rte_Call_RP_ActvRetProvParameters_Get_ActvRetSteerSpdFact(&SteerSpdFact_Val);

   /* TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/ActvRetSpdFac */
   (void) Rte_Read_RP_ActvRetFactors_ActvRetSpdFac(&ActvRetSpdFac);

   /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_ActvRetSpdFac/Switch
      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_ActvRetSpdFac/Switch: Omitted compa
      rison with constant.
      # combined # Logical: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_ActvRetSpdFac
      /Valid_xFactMinI_ActiveRetSpeedFactor/LogicalOp */
   if (ActvRetSpdFac <= ADT_ActvRetSpdFac_UpperLimit) {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_ActvRetSpdFac/Switch */
      x_FctCoSpeedFact_ldU16 = ActvRetSpdFac;
   }
   else {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_ActvRetSpdFac/Switch */
      x_FctCoSpeedFact_ldU16 = 1024 /* 1. */;
   }

   /* TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/SteerAng */
   (void) Rte_Read_RP_SteerAng_SteerAng(&SteerAng);

   /* Logical: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAng/Valid_SteerAng/Lo
      gicalOp
      # combined # Relational: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAng/V
      alid_SteerAng/RelationalOp1
      # combined # Relational: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAng/V
      alid_SteerAng/RelationalOp */
   f_SteeringAngleValidIsValid_ldB = (SteerAng <= ADT_SteerAng_UpperLimit) && (SteerAng >=
    ADT_SteerAng_LowerLimit);

   /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAng/Switch
      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAng/Switch: Omitted comparison
       with constant. */
   if (f_SteeringAngleValidIsValid_ldB) {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAng/Switch */
      w_SteerAng_ldS16 = SteerAng;
   }
   else {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAng/Switch */
      w_SteerAng_ldS16 = 0;
   }

   /* Sign: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Sign */
   if (w_SteerAng_ldS16 < 0) {
      AbsSteerAng_ldU16 = (uint16) (-w_SteerAng_ldS16);
      y_SteeringAngleSign_ldS8 = -1;
   }
   else {
      AbsSteerAng_ldU16 = (uint16) w_SteerAng_ldS16;
      y_SteeringAngleSign_ldS8 = (sint8) (w_SteerAng_ldS16 > 0);
   }

   /* call of function: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNominalS
      teeringAngleSpeed/InterpolationOverSteeringAngle/SSCP_RP_ProvideParameters_Get_vActRet_Nominal
      SteeringSpeed_XAU16 */
   (void) Rte_Call_RP_ActvRetProvParameters_Get_ActvRetNomSteerSpd(&NomSteerSpd_Val, AbsAvgVehSpd,
    AbsSteerAng_ldU16);

   /* Product: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNominalSteeringAn
      gleSpeed/InterpolationOverSteeringAngle/NominalSteeringSpeed
      # combined # Product: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNomi
      nalSteeringAngleSpeed/InterpolationOverSteeringAngle/Product */
   v_RawNominalSteeringSpeed_ldS16 = (sint16) ((((sint32) NomSteerSpd_Val) * ((sint32) (-((sint32)
    (y_SteeringAngleSign_ldS8 * 8))))) >> 3);

   /* TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/SteerAngSt */
   (void) Rte_Read_RP_SteerAng_SteerAngSt(&SteerAngSt);

   /* TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/RP_SteerAngSpd */
   (void) Rte_Read_RP_SteerAngSpd_SteerAngSpd(&SteerAngSpd);

   /* Logical: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAngSpd/Valid_vApplI_S
      teeringAngleSpeed/LogicalOp
      # combined # Relational: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAngSp
      d/Valid_vApplI_SteeringAngleSpeed/RelationalOp1
      # combined # Relational: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAngSp
      d/Valid_vApplI_SteeringAngleSpeed/RelationalOp */
   f_SteeringAngleSpeedIsValid_ldB = (SteerAngSpd <= ADT_SteerAngSpd_UpperLimit) && (SteerAngSpd >=
    ADT_SteerAngSpd_LowerLimit);

   /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/HandleInvalidSignals/x_Targ
      etRampFactor
      ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/HandleInvalidSignals/x_TargetRampFa
      ctor: Omitted comparison with constant.
      # combined # Logical: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/HandleInvalid
      Signals/f_ValidSignals
      # combined # Logical: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/SteeringAngleIsVail
      d
      # combined # Logical: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Valid_AbsAvgVehSpd/
      LogicalOp
      # combined # Logical: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/f_RPValid
      # combined # Relational: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/f_RPExactly
      # combined # Relational: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/f_RPRaw */
   if ((AbsAvgVehSpd <= ADT_AbsAvgVehSpd_UpperLimit) && (((SteerAngSt == CM_SYMBOL_RP_RAW) ||
    (SteerAngSt == CM_SYMBOL_RP_EXACTLY)) && f_SteeringAngleValidIsValid_ldB) &&
    f_DriverTorqueIsValid_ldB && f_SteeringAngleSpeedIsValid_ldB) {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/HandleInvalidSignals/x_T
         argetRampFactor */
      x_TargetRampFactor_ldU16 = 32768 /* 1. */;
   }
   else {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/HandleInvalidSignals/x_T
         argetRampFactor */
      x_TargetRampFactor_ldU16 = 0;
   }

   /* Sum: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/HandleInvalidSignals/RateLim_x
      _RampFactor/changeRate */
   x_RampFactor_changeRate_ldS32 = ((sint32) x_TargetRampFactor_ldU16) - ((sint32)
    x_RampFactor_z_sdU16);

   /* TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/SteerSpdGradAftInvld */
   (void)
    Rte_Call_RP_ActvRetProvParameters_Get_ActvRetSteerSpdGradAftInvld(&SteerSpdGradAftInvld_Val);
   Aux_ldS32 = (sint32) SteerSpdGradAftInvld_Val;

   /* MinMax: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/HandleInvalidSignals/RateLi
      m_x_RampFactor/Min */
   if (x_RampFactor_changeRate_ldS32 < Aux_ldS32) {
      x_RampFactor_min_ldS32 = x_RampFactor_changeRate_ldS32;
   }
   else {
      x_RampFactor_min_ldS32 = Aux_ldS32;
   }

   /* Sum: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/HandleInvalidSignals/RateLim_x
      _RampFactor/RateLimSum */
   x_RampFactor_ldS32 = x_RampFactor_min_ldS32 + ((sint32) x_RampFactor_z_sdU16);

   /* Unit delay: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/HandleInvalidSignals/Ra
      teLim_x_RampFactor/x_RampFactor_z */
   x_RampFactor_z_sdU16 = (uint16) x_RampFactor_ldS32;

   /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAngSpd/Switch
      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAngSpd/Switch: Omitted compari
      son with constant. */
   if (f_SteeringAngleSpeedIsValid_ldB) {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAngSpd/Switch */
      v_SteeringAngleSpeed_ldS16 = SteerAngSpd;
   }
   else {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_SteerAngSpd/Switch */
      v_SteeringAngleSpeed_ldS16 = 0;
   }

   /* Sum: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/v_Deviation
      # combined # Product: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/HandleInvalid
      Signals/NominalSteeringSpeed
      # combined # Product: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNomi
      nalSteeringAngleSpeed/NominalSteeringSpeed
      # combined # Product: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNomi
      nalSteeringAngleSpeed/x_SteeringSpeedFactor2
      # combined # Product: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNomi
      nalSteeringAngleSpeed/x_SteeringSpeedFactor1
      # combined # Rescaler: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNom
      inalSteeringAngleSpeed/Rescaler1
      # combined # Rescaler: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/HandleInvali
      dSignals/Rescaler */
   v_Deviation_ldS32 = ((sint32) ((((sint32) ((((sint32) (sint16) ((((sint32) (sint16) ((((sint32)
    (ActvRetSpdFacFilt_ldS32 >> 10)) * ((sint32) SteerSpdFact_Val)) >> 7)) * ((sint32)
    x_FctCoSpeedFact_ldU16)) >> 10)) * ((sint32) v_RawNominalSteeringSpeed_ldS16)) >> 3)) *
    ((sint32) (sint16) (x_RampFactor_ldS32 >> 8))) >> 7)) - (((sint32) v_SteeringAngleSpeed_ldS16) *
    128);
   if (v_Deviation_ldS32 > v_MaxRetSpeedDiff_ldS32) {
      /* Merge: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/Sat2Range_vActRet_ReturnS
         peedDiff/Merge
         update of variable(s) associated with ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnT
         orque/Sat2Range_vActRet_ReturnSpeedDiff/upperLimExceeded/MAX_vActRet_ReturnSpeedDiff_xds16_
         in */
      v_ReturnSpeedDiff_ldS32 = v_MaxRetSpeedDiff_ldS32;
   }
   else {
      /* SLLocal: Default storage class for local variables | Width: 32 */
      sint32 v_MinRetSpeedDiff_ldS32; /* LSB: 2^-10 OFF: -0 MIN/MAX: -2097152 .. 2097151.99902344 */

      /* Rescaler: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/Sat2Range_vActRet_Retu
         rnSpeedDiff/Rescaler1 */
      v_MinRetSpeedDiff_ldS32 = ((sint32) ADT_ActvRetRetSpdDiff_LowerLimit) * 128;
      if (v_Deviation_ldS32 < v_MinRetSpeedDiff_ldS32) {
         /* Merge: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/Sat2Range_vActRet_Retu
            rnSpeedDiff/Merge
            update of variable(s) associated with ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveRetu
            rnTorque/Sat2Range_vActRet_ReturnSpeedDiff/lowerLimExceeded/MIN_vActRet_ReturnSpeedDiff_
            xds16_in */
         v_ReturnSpeedDiff_ldS32 = v_MinRetSpeedDiff_ldS32;
      }
      else {
         /* Merge: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/Sat2Range_vActRet_Retu
            rnSpeedDiff/Merge
            update of variable(s) associated with ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveRetu
            rnTorque/Sat2Range_vActRet_ReturnSpeedDiff/withinLimits/v_SteeringSpeedDiff_in */
         v_ReturnSpeedDiff_ldS32 = v_Deviation_ldS32;
      }
   }

   /* TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/SteerSpdAmp */
   (void) Rte_Call_RP_ActvRetProvParameters_Get_ActvRetSteerSpdAmp(&SteerSpdAmp_Val);

   /* Product: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturnTorqu
      e/m_MotorTorque2
      # combined # Product: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActi
      veReturnTorque/m_MotorTorque1
      # combined # TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/MotTrqGain */
   m_MotorTorque2_ldS32 = (sint32) ((((sint32) Rte_IrvRead_ActRetI_CalcActvRetTrq_IRV_MotTrqGain())
    * ((sint32) ((v_ReturnSpeedDiff_ldS32 * ((sint32) SteerSpdAmp_Val)) >> 14))) >> 10);
   if (m_MotorTorque2_ldS32 > ((sint32) (((uint32) MaxMotTrq_Val_a) << 4))) {
      /* Merge: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturnTorq
         ue/SymSat_m_MotorTorque2/Merge
         update of variable(s) associated with ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnT
         orque/CalculateActiveReturnTorque/SymSat_m_MotorTorque2/upperLimExceeded/MaxMotTrq_in */
      m_MotorTorque2_ldS16 = (sint16) (((uint16) MaxMotTrq_Val_a) << 4);
   }
   else {
      /* SLLocal: Default storage class for local variables | Width: 16 */
      sint16 m_MotorTorque2_negLim_ldS16; /* 
         Unit: Nm
         LSB: 2^-10 OFF: 0 MIN/MAX: -32 .. 31.9990234375 */

      /* Gain: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturnTorqu
         e/SymSat_m_MotorTorque2/Gain */
      m_MotorTorque2_negLim_ldS16 = (sint16) (-((sint16) (((uint16) MaxMotTrq_Val_a) << 4)));
      if (m_MotorTorque2_ldS32 < ((sint32) m_MotorTorque2_negLim_ldS16)) {
         /* Merge: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturnT
            orque/SymSat_m_MotorTorque2/Merge
            update of variable(s) associated with ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveRetu
            rnTorque/CalculateActiveReturnTorque/SymSat_m_MotorTorque2/lowerLimExceeded/m_MotorTorqu
            e2_negLim_in */
         m_MotorTorque2_ldS16 = m_MotorTorque2_negLim_ldS16;
      }
      else {
         /* Merge: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturnT
            orque/SymSat_m_MotorTorque2/Merge
            update of variable(s) associated with ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveRetu
            rnTorque/CalculateActiveReturnTorque/SymSat_m_MotorTorque2/withinLimits/m_ActRetTrqwithG
            ain_in */
         m_MotorTorque2_ldS16 = (sint16) m_MotorTorque2_ldS32;
      }
   }

   /* TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/RP_LoadFacRat */
   (void) Rte_Read_RP_LoadFacRat_LoadFacRat(&LoadFacRat);

   /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_xCompIncFricI_ActiveRetBoos
      t/Switch
      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_xCompIncFricI_ActiveRetBoost/Switch
      : Omitted comparison with constant.
      # combined # Logical: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_xCompIncFricI
      _ActiveRetBoost/Valid_xCompIncFricI_ActiveRetBoost/LogicalOp */
   if (LoadFacRat <= ADT_LoadFacRat_UpperLimit) {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_xCompIncFricI_ActiveRetB
         oost/Switch */
      x_LoadFactorRatio_ldU16 = LoadFacRat;
   }
   else {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_xCompIncFricI_ActiveRetB
         oost/Switch */
      x_LoadFactorRatio_ldU16 = 0;
   }

   /* Sum: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturnTorque/m_
      TotalTorque
      # combined # Product: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActi
      veReturnTorque/m_MotorTorque3 */
   m_TotalTorque_ldS32 = ((sint32) m_MotorTorque2_ldS16) + ((sint32) ((((sint32)
    m_MotorTorque2_ldS16) * ((sint32) x_LoadFactorRatio_ldU16)) >> 10));
   if (m_TotalTorque_ldS32 > ((sint32) (((uint32) MaxMotTrqAftLoadFac_Val_a) << 4))) {
      /* Merge: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturnTorq
         ue/SymSat_m_TotalTorque/Merge
         update of variable(s) associated with ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnT
         orque/CalculateActiveReturnTorque/SymSat_m_TotalTorque/upperLimExceeded/MaxMotTrqAftLoadFac
         _in */
      m_TotalTorque_ldS16 = (sint16) (((uint16) MaxMotTrqAftLoadFac_Val_a) << 4);
   }
   else {
      /* SLLocal: Default storage class for local variables | Width: 16 */
      sint16 m_TotalTorque_negLim_ldS16; /* 
         Unit: Nm
         LSB: 2^-10 OFF: 0 MIN/MAX: -32 .. 31.9990234375 */

      /* Gain: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturnTorqu
         e/SymSat_m_TotalTorque/Gain */
      m_TotalTorque_negLim_ldS16 = (sint16) (-((sint16) (((uint16) MaxMotTrqAftLoadFac_Val_a) <<
       4)));
      if (m_TotalTorque_ldS32 < ((sint32) m_TotalTorque_negLim_ldS16)) {
         /* Merge: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturnT
            orque/SymSat_m_TotalTorque/Merge
            update of variable(s) associated with ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveRetu
            rnTorque/CalculateActiveReturnTorque/SymSat_m_TotalTorque/lowerLimExceeded/m_TotalTorque
            _negLim_in */
         m_TotalTorque_ldS16 = m_TotalTorque_negLim_ldS16;
      }
      else {
         /* Merge: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturnT
            orque/SymSat_m_TotalTorque/Merge
            update of variable(s) associated with ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveRetu
            rnTorque/CalculateActiveReturnTorque/SymSat_m_TotalTorque/withinLimits/m_ActRetTrqwithGa
            in_in */
         m_TotalTorque_ldS16 = (sint16) m_TotalTorque_ldS32;
      }
   }

   /* TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/RP_GearSign */
   (void) Rte_Read_RP_GearSign_GearSign(&GearSign);

   /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_GearSign/Switch
      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_GearSign/Switch: Omitted comparison
       with constant.
      # combined # Logical: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_GearSign/Vali
      d_xApplI_GearSign/LogicalOp
      # combined # Relational: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_GearSign/V
      alid_xApplI_GearSign/RelationalOp1
      # combined # Relational: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_GearSign/V
      alid_xApplI_GearSign/RelationalOp */
   if ((GearSign <= ADT_GearSign_UpperLimit) && (GearSign >= ADT_GearSign_LowerLimit)) {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_GearSign/Switch */
      x_GearSign_ldS8 = GearSign;
   }
   else {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_GearSign/Switch */
      x_GearSign_ldS8 = 0;
   }

   /* TargetLink inport: ActiveReturn/ActRetI_CalcActvRetTrq/ActvRetFuncFac */
   (void) Rte_Read_RP_ActvRetFactors_ActvRetFuncFac(&ActvRetFuncFac);

   /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_ActiveRetFuncFac/Switch
      ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_ActiveRetFuncFac/Switch: Omitted co
      mparison with constant.
      # combined # Logical: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_ActiveRetFunc
      Fac/Valid_ActvRetFuncFac/LogicalOp */
   if (ActvRetFuncFac <= ADT_ActvRetFuncFac_UpperLimit) {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_ActiveRetFuncFac/Switch
      */
      x_FctCoFuncFact_ldU16 = ActvRetFuncFac;
   }
   else {
      /* Switch: ActiveReturn/ActRetI_CalcActvRetTrq/SignalProcessing/Subst_ActiveRetFuncFac/Switch
      */
      x_FctCoFuncFact_ldU16 = 1024 /* 1. */;
   }

   /* # combined # TargetLink outport: ActiveReturn/ActRetI_CalcActvRetTrq/ActvRetMotTrq4Chk
      # combined # Product: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActi
      veReturnTorque/MotTrq4Check
      # combined # Product: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActi
      veReturnTorque/x_ActiveRetFuncFactor2
      # combined # Product: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActi
      veReturnTorque/x_ActiveRetFuncFactor
      # combined # Rescaler: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateAct
      iveReturnTorque/Rescaler */
   (void) Rte_Write_PP_ActvRetMotTrq4Chk_ActvRetMotTrq4Chk((sint16) ((((sint32) m_TotalTorque_ldS16)
    * ((sint32) (((sint16) x_GearSign_ldS8) * ((sint16) ((((sint32) x_FctCoFuncFact_ldU16) *
    ((sint32) (ActvRetTrqFacFilt_ldS32 >> 10))) >> 10))))) >> 10));

   /* TargetLink outport: ActiveReturn/ActRetI_CalcActvRetTrq/ActvRetRetSpdDiff
      # combined # Rescaler: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/ReturnSpeedD
      iff */
   Rte_IrvWrite_ActRetI_CalcActvRetTrq_IRV_ActvRetRetSpdDiff((sint16) (v_ReturnSpeedDiff_ldS32 >>
    7));

   /* TargetLink outport: ActiveReturn/ActRetI_CalcActvRetTrq/ActvRetSpdFacFilt */
   Rte_IrvWrite_ActRetI_CalcActvRetTrq_IRV_ActvRetSpdFacFilt(ActvRetSpdFacFilt_ldS32);

   /* Unit delay: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateActiveReturnTo
      rque/FiltDriverTorqueDependentFactor/xActRet_TorqueFactorFilt_last */
   *(Rte_Pim_PIM_ActvRetTrqFacFilt()) = ActvRetTrqFacFilt_ldS32;

   /* Unit delay: ActiveReturn/ActRetI_CalcActvRetTrq/CalcActiveReturnTorque/CalculateNominalSteerin
      gAngleSpeed/FiltSteeringSpeedDependentFactor/xActRet_TorqueFactorFilt_last */
   *(Rte_Pim_PIM_ActvRetSpdFacFilt()) = ActvRetSpdFacFilt_ldS32;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetI_InterpolCharacteristics
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturn_CODE) ActRetI_InterpolCharacteristics(void)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   IDT_AbsAvgVehSpd AbsAvgVehSpd; /* LSB: 2^-6 OFF: 0 MIN/MAX: 0 .. 500 */
   uint16 MotTrqGain_Val; /* LSB: 2^-10 OFF: 0 MIN/MAX: 0 .. 3 */
   uint16 v_AbsAvgVehSpdSubst_ldU16; /* LSB: 2^-6 OFF: 0 MIN/MAX: 0 .. 500 */

   /* TargetLink inport: ActiveReturn/ActRetI_InterpolCharacteristics/AbsAvgVehSpd */
   (void) Rte_Read_RP_VehSpd_AbsAvgVehSpd(&AbsAvgVehSpd);

   /* Switch: ActiveReturn/ActRetI_InterpolCharacteristics/Subst_AbsAvgVehSpd/Switch
      ActiveReturn/ActRetI_InterpolCharacteristics/Subst_AbsAvgVehSpd/Switch: Omitted comparison wit
      h constant.
      # combined # Logical: ActiveReturn/ActRetI_InterpolCharacteristics/Subst_AbsAvgVehSpd/Valid_Ab
      sAvgVehSpd/LogicalOp */
   if (AbsAvgVehSpd <= ADT_AbsAvgVehSpd_UpperLimit) {
      /* Switch: ActiveReturn/ActRetI_InterpolCharacteristics/Subst_AbsAvgVehSpd/Switch */
      v_AbsAvgVehSpdSubst_ldU16 = AbsAvgVehSpd;
   }
   else {
      /* Switch: ActiveReturn/ActRetI_InterpolCharacteristics/Subst_AbsAvgVehSpd/Switch */
      v_AbsAvgVehSpdSubst_ldU16 = 5120 /* 80. */;
   }

   /* call of function: ActiveReturn/ActRetI_InterpolCharacteristics/SSCP_RP_ProvideParameters_Get_x
      ActRet_MotorTorqueGain_XAU16 */
   (void) Rte_Call_RP_ActvRetProvParameters_Get_ActvRetMotTrqGain(&MotTrqGain_Val,
    v_AbsAvgVehSpdSubst_ldU16);

   /* TargetLink outport: ActiveReturn/ActRetI_InterpolCharacteristics/MotTrqGain */
   Rte_IrvWrite_ActRetI_InterpolCharacteristics_IRV_MotTrqGain(MotTrqGain_Val);
}

/* end of memory section 'CODE' */
#define ActiveReturn_STOP_SEC_CODE
#include "ActiveReturn_MemMap.h"

/*------------------------------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/
#endif /* IACTRET_MAIN_GG_C */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/

