/**************************************************************************************************\
 *** Copyright (c) Robert Bosch Automotive Steering GmbH, Germany
 *** All rights reserved
 ***
 *** Generated by: Raghul Gnanaseelan (MS/ESP3-VM)
 ***
 *** Generated with:
 *** MathWorks MATLAB                            23.2.0.2668659 (R2023b) Update 9
 *** dSPACE TargetLink Production Code Generator 23.1p2 (Release 2023-B)
 *** AS --- MBSD environment                     R2402
 *** AS --- MBSD version (tag or branch:commit)  R2402-RC2:dca08e23
 *** AS --- Train project/repo                   ASMPAPP/asmp-dev
 *** AS --- Train version (tag or branch:commit) develop:901d3eaf
\**************************************************************************************************/
/**************************************************************************************************\
 *** 
 *** Simulink model       : ActiveReturnCheck_sm
 *** TargetLink subsystem : ActiveReturnCheck_sm/ActiveReturnCheck
 *** Codefile             : IActRet_Check_gg.c
 *** Language             : C
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-09-04 17:30:21
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Classic AUTOSAR
 *** AUTOSAR version                          : 22-11
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : AvoidPotentiallyUndefinedShiftsBasedOnWorstCaseRange
 s
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : disabled
 *** State activity encoding limit            : 1
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 100
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 2023-B\Matlab\Tl\
 ***                                            config\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 2023-B\Matlab\Tl\
 ***                                            XML\CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS         CORRESPONDING SIMULINK SUBSYSTEM
 *** SActRetChk1    ActiveReturnCheck
 *** SActRetChk2    ActiveReturnCheck/ActRetI_DiSwt
 *** SActRetChk3    ActiveReturnCheck/ActRetI_Mon
 *** SActRetChk4    ActiveReturnCheck/ActRetI_Satn
 *** SActRetChk5    ActiveReturnCheck/Additional_Design_Information
 *** SActRetChk6    ActiveReturnCheck/ActRetI_Mon/DiagData_SetEventEntry
 *** SActRetChk7    ActiveReturnCheck/ActRetI_Mon/MotorTorqueMonitoring
 *** SActRetChk8    ActiveReturnCheck/ActRetI_Mon/TorsionBarTorqueMonitoring
 *** SActRetChk9    ActiveReturnCheck/ActRetI_Mon/MotorTorqueMonitoring/Valid_mActRet_MotTrqSaturate
 ***                d
 *** SActRetChk10   ActiveReturnCheck/ActRetI_Satn/CalibrationData
 *** SActRetChk11   ActiveReturnCheck/ActRetI_Satn/Sat_mActRet_MotTrqSaturated
 *** SActRetChk12   ActiveReturnCheck/ActRetI_Satn/SignalProcessing
 *** SActRetChk13   ActiveReturnCheck/ActRetI_Satn/CalibrationData/SSCP_RP_ActvRetProvParameters_Get
 ***                _ActvRetMaxMotTrqDepOnSteerAng
 *** SActRetChk14   ActiveReturnCheck/ActRetI_Satn/CalibrationData/SSCP_RP_ActvRetProvParameters_Get
 ***                _ActvRetMaxMotTrqDepOnVehSpd
 *** SActRetChk15   ActiveReturnCheck/ActRetI_Satn/CalibrationData/SSCP_RP_ActvRetProvParameters_Get
 ***                _ActvRetMaxMotTrqDepOnSteerAng/Src
 *** SActRetChk16   ActiveReturnCheck/ActRetI_Satn/CalibrationData/SSCP_RP_ActvRetProvParameters_Get
 ***                _ActvRetMaxMotTrqDepOnSteerAng/Src/MaxMotorTorqueDepOnSteerAng
 *** SActRetChk17   ActiveReturnCheck/ActRetI_Satn/CalibrationData/SSCP_RP_ActvRetProvParameters_Get
 ***                _ActvRetMaxMotTrqDepOnVehSpd/Src
 *** SActRetChk18   ActiveReturnCheck/ActRetI_Satn/CalibrationData/SSCP_RP_ActvRetProvParameters_Get
 ***                _ActvRetMaxMotTrqDepOnVehSpd/Src/MaxMotorTorqueDepOnVehSpd
 *** SActRetChk19   ActiveReturnCheck/ActRetI_Satn/Sat_mActRet_MotTrqSaturated/lowerLimExceeded
 *** SActRetChk20   ActiveReturnCheck/ActRetI_Satn/Sat_mActRet_MotTrqSaturated/upperLimExceeded
 *** SActRetChk21   ActiveReturnCheck/ActRetI_Satn/Sat_mActRet_MotTrqSaturated/withinLimits
 *** SActRetChk22   ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Valid_mApplI_TorsionBarTorque
 *** SActRetChk23   ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Valid_vVehSpI_AbsMaxSafeVehSpd
 *** SActRetChk24   ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Valid_wApplI_SteeringAngle
 *** SActRetChk25   ActiveReturnCheck/Additional_Design_Information/Appendix
 *** SActRetChk26   ActiveReturnCheck/Additional_Design_Information/Calibration_Data
 *** SActRetChk27   ActiveReturnCheck/Additional_Design_Information/Configuration_Data
 *** SActRetChk28   ActiveReturnCheck/Additional_Design_Information/Dependencies
 *** SActRetChk29   ActiveReturnCheck/Additional_Design_Information/Integration_Hints
 *** SActRetChk30   ActiveReturnCheck/Additional_Design_Information/Interfaces
 *** SActRetChk31   ActiveReturnCheck/Additional_Design_Information/Internals
 *** SActRetChk32   ActiveReturnCheck/Additional_Design_Information/Safety_Concept
 *** SActRetChk33   ActiveReturnCheck/Additional_Design_Information/Short_Description
 *** SActRetChk34   ActiveReturnCheck/Additional_Design_Information/Calibration_Data/imageCalibratio
 ***                nData
 *** SActRetChk35   ActiveReturnCheck/Additional_Design_Information/Integration_Hints/imageScheduler
 *** SActRetChk36   ActiveReturnCheck/Additional_Design_Information/Interfaces/imageDataInterfaces
 *** SActRetChk37   ActiveReturnCheck/Additional_Design_Information/Interfaces/imageFunctionalInterf
 ***                aces
 *** SActRetChk38   ActiveReturnCheck/Additional_Design_Information/Internals/imageInternalFunction
 *** SActRetChk39   ActiveReturnCheck/Additional_Design_Information/Internals/imageMeasuredValues
 *** 
 *** SUBSYS         CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE        CORRESPONDING STATEFLOW NODE                    DESCRIPTION
 *** CActRetChk0    ActiveReturnCheck_sm                            
 *** CActRetChk1    ActiveReturnCheck/Scheduler                     
 *** CActRetChk1                                                    
 *** CActRetChk1                                                    
 *** CActRetChk1                                                    
 *** CActRetChk2    ActiveReturnCheck/ActRetI_Mon/MonitorStateHandl
 ***                er                                              
 *** CActRetChk2                                                    
 *** CActRetChk3    ActiveReturnCheck/ActRetI_Mon/MonitorStateHandl
 ***                er.PASSED                                       
 *** CActRetChk4    ActiveReturnCheck/ActRetI_Mon/MonitorStateHandl
 ***                er.FAILED                                       
 *** 
 *** TargetLink version      : 23.1p2 from 23-May-2024
 *** Code generator version  : Build Id 23.1.0.24 from 2024-05-16 17:28:10
\**************************************************************************************************/

#ifndef IACTRET_CHECK_GG_C
#define IACTRET_CHECK_GG_C

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "Rte_ActiveReturnCheck_Type.h"
#include "Rte_ActiveReturnCheck.h"
#include "IEventHistory_hh.h"
#include "IActRet_Check_gg.h"

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   AS_STATIC_MACRO_MERGEABLE: mergeable preprocessor macros; will be generated into source-file
\**************************************************************************************************/
#define SF_FAILED ((uint8) 2)
#define SF_PASSED ((uint8) 1)

/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/* start of memory section 'CODE' */
#define ActiveReturnCheck_START_SEC_CODE
#include "ActiveReturnCheck_MemMap.h"
/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetI_DisableSwitch
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCheck_CODE) ActRetI_DisableSwitch(void)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   IDT_ActvRetMotTrqSatn IRV_ActvRetMotTrqSatn; /* LSB: 2^-10 OFF: 0 MIN/MAX: -3 .. 3 */

   /* TargetLink Inport: ActiveReturnCheck/ActRetI_DiSwt/ActvRetMotTrqSatn */
   IRV_ActvRetMotTrqSatn = Rte_IrvRead_ActRetI_DiSwt_IRV_ActvRetMotTrqSatn();

   /* Switch: ActiveReturnCheck/ActRetI_DiSwt/Switch
      ActiveReturnCheck/ActRetI_DiSwt/Switch: Omitted comparison with constant.
      # combined # TargetLink Inport: ActiveReturnCheck/ActRetI_DiSwt/ActvRetDi */
   if (Rte_IrvRead_ActRetI_DiSwt_IRV_ActvRetDi()) {
      /* # combined # TargetLink Outport: ActiveReturnCheck/ActRetI_DiSwt/ActvRetMotTrq
         # combined # Switch: ActiveReturnCheck/ActRetI_DiSwt/Switch */
      (void) Rte_Write_PP_ActvRetMotTrq_ActvRetMotTrq(0);
   }
   else {
      /* # combined # TargetLink Outport: ActiveReturnCheck/ActRetI_DiSwt/ActvRetMotTrq
         # combined # Switch: ActiveReturnCheck/ActRetI_DiSwt/Switch */
      (void) Rte_Write_PP_ActvRetMotTrq_ActvRetMotTrq(IRV_ActvRetMotTrqSatn);
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetI_Monitoring
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCheck_CODE) ActRetI_Monitoring(void)
{
   /* SFLocalInit: Default storage class for local variables with init values | Width: 8 */
   uint8 s_MonitorStatus_ldU8;

   /* SFStaticLocalInit: Default storage class for static local variables with initvalue | Width: 8
   */
   static uint8 s_MonitorStateHandler_ns = 0;

   /* SLLocal: Default storage class for local variables | Width: 16 */
   IDT_AbsMaxSafeVehSpd IRV_ActvRetAbsMaxSafeVehSpdSat; /* LSB: 2^-6 OFF: 0 MIN/MAX: 0 .. 500 */
   IDT_ActvRetAbsSteerAngSat IRV_ActvRetAbsSteerAngSat; /* LSB: 0.1 OFF: 0 MIN/MAX: 0 .. 1000 */
   IDT_ActvRetAbsTorsBarTrqSat IRV_ActvRetAbsTorsBarTrqSat; /* LSB: 2^-10 OFF: 0 MIN/MAX: 0 .. 25 */
   IDT_ActvRetMaxMotTrqMin IRV_ActvRetMaxMotTrqMin; /* LSB: 2^-10 OFF: 0 MIN/MAX: 0 .. 3 */
   IDT_ActvRetMotTrqSatn IRV_ActvRetMotTrqSatn_a; /* LSB: 2^-10 OFF: 0 MIN/MAX: -3 .. 3 */

   /* SLLocal: Default storage class for local variables | Width: 8 */
   boolean ActvRetDi_ldB;
   uint8 MaxTBT4ShtDwn_Val; /* LSB: 2^-4 OFF: 0 MIN/MAX: 0 .. 15 */

   /* TargetLink Inport: ActiveReturnCheck/ActRetI_Mon/ActvRetAbsMaxSafeVehSpdSat */
   IRV_ActvRetAbsMaxSafeVehSpdSat = Rte_IrvRead_ActRetI_Mon_IRV_ActvRetAbsMaxSafeVehSpdSat();

   /* TargetLink Inport: ActiveReturnCheck/ActRetI_Mon/ActvRetAbsSteerAngSat */
   IRV_ActvRetAbsSteerAngSat = Rte_IrvRead_ActRetI_Mon_IRV_ActvRetAbsSteerAngSat();

   /* TargetLink Inport: ActiveReturnCheck/ActRetI_Mon/ActvRetAbsTorsBarTrqSat */
   IRV_ActvRetAbsTorsBarTrqSat = Rte_IrvRead_ActRetI_Mon_IRV_ActvRetAbsTorsBarTrqSat();

   /* TargetLink Inport: ActiveReturnCheck/ActRetI_Mon/ActvRetMotTrqSatn */
   IRV_ActvRetMotTrqSatn_a = Rte_IrvRead_ActRetI_Mon_IRV_ActvRetMotTrqSatn();

   /* TargetLink Inport: ActiveReturnCheck/ActRetI_Mon/ActvRetMaxTBT4ShutDown */
   (void) Rte_Call_RP_ActvRetProvParameters_Get_ActvRetMaxTBT4ShtDwn(&MaxTBT4ShtDwn_Val);

   /* TargetLink Inport: ActiveReturnCheck/ActRetI_Mon/ActvRetMaxMotTrqMin */
   IRV_ActvRetMaxMotTrqMin = Rte_IrvRead_ActRetI_Mon_IRV_ActvRetMaxMotTrqMin();

   /* Logic: ActiveReturnCheck/ActRetI_Mon/Logical_Operator2
      # combined # Logic: ActiveReturnCheck/ActRetI_Mon/MotorTorqueMonitoring/MotMonFailed
      # combined # Logic: ActiveReturnCheck/ActRetI_Mon/TorsionBarTorqueMonitoring/Logical_Operator1
      # combined # RelationalOperator: ActiveReturnCheck/ActRetI_Mon/TorsionBarTorqueMonitoring/f_Tb
      tBelow
      # combined # RelationalOperator: ActiveReturnCheck/ActRetI_Mon/TorsionBarTorqueMonitoring/f_Mo
      tTrqNotSaturated */
   ActvRetDi_ldB = ((IRV_ActvRetMotTrqSatn_a != 0) && (((uint16) (IRV_ActvRetAbsTorsBarTrqSat >> 6))
    >= ((uint16) MaxTBT4ShtDwn_Val))) || ((IRV_ActvRetMotTrqSatn_a > ((sint16)
    IRV_ActvRetMaxMotTrqMin)) || (IRV_ActvRetMotTrqSatn_a < ((sint16) (-((sint16)
    IRV_ActvRetMaxMotTrqMin))))) || (*(Rte_Pim_PIM_ActvRetDi()));

   /* In the first function call we have to call the
      EvtHstI_HlSetEventEntry() in passed state
      to register this MonitorID.
      If an error occured we call the function once
      again in failed state. */

   /* Begin execution of chart ActiveReturnCheck/ActRetI_Mon/MonitorStateHandler */
   switch (s_MonitorStateHandler_ns) {
      case SF_PASSED: {
         /* Begin execution of state ActiveReturnCheck/ActRetI_Mon/MonitorStateHandler.PASSED */
         if (ActvRetDi_ldB) {
            /* State transition from ActiveReturnCheck/ActRetI_Mon/MonitorStateHandler.PASSED to Act
               iveReturnCheck/ActRetI_Mon/MonitorStateHandler.FAILED */
            s_MonitorStateHandler_ns = SF_FAILED;
            s_MonitorStatus_ldU8 = HL_MONITOR_STATUS_FAILED;

            /* # combined # BusOutport: ActiveReturnCheck/ActRetI_Mon/DiagData_SetEventEntry/Set_Act
               vRetDiagData
               # combined # Rescaler: ActiveReturnCheck/ActRetI_Mon/DiagData_SetEventEntry/Rescaler3
               # combined # Rescaler: ActiveReturnCheck/ActRetI_Mon/DiagData_SetEventEntry/Rescaler
               # combined # Rescaler: ActiveReturnCheck/ActRetI_Mon/DiagData_SetEventEntry/Rescaler2
               # combined # Rescaler: ActiveReturnCheck/ActRetI_Mon/DiagData_SetEventEntry/Rescaler1
                */
            (void) Rte_Call_RP_ActvRetDiagData_Set_ActvRetDiagData(IRV_ActvRetMotTrqSatn_a,
             IRV_ActvRetAbsTorsBarTrqSat, IRV_ActvRetAbsMaxSafeVehSpdSat,
             IRV_ActvRetAbsSteerAngSat);

            /* # combined # BusOutport: ActiveReturnCheck/ActRetI_Mon/DiagData_SetEventEntry/Set_Act
               vRetEntry
               # combined # Rescaler: ActiveReturnCheck/ActRetI_Mon/DiagData_SetEventEntry/Rescaler4
                */
            (void) Rte_Call_RP_ActvRetSetEveEntry_Set_ActvRetEntry(s_MonitorStatus_ldU8,
             MONID_ACTIVE_RETURN, 0);
         }

         /* End execution of state ActiveReturnCheck/ActRetI_Mon/MonitorStateHandler.PASSED */
         break;
      }
      case SF_FAILED: {
         /* Begin execution of state ActiveReturnCheck/ActRetI_Mon/MonitorStateHandler.FAILED */

         /* End execution of state ActiveReturnCheck/ActRetI_Mon/MonitorStateHandler.FAILED */
         break;
      }
      default: {
         /* State transition to ActiveReturnCheck/ActRetI_Mon/MonitorStateHandler.PASSED */
         s_MonitorStateHandler_ns = SF_PASSED;
         s_MonitorStatus_ldU8 = HL_MONITOR_STATUS_PASSED;

         /* # combined # BusOutport: ActiveReturnCheck/ActRetI_Mon/DiagData_SetEventEntry/Set_ActvRe
            tDiagData
            # combined # Rescaler: ActiveReturnCheck/ActRetI_Mon/DiagData_SetEventEntry/Rescaler3
            # combined # Rescaler: ActiveReturnCheck/ActRetI_Mon/DiagData_SetEventEntry/Rescaler
            # combined # Rescaler: ActiveReturnCheck/ActRetI_Mon/DiagData_SetEventEntry/Rescaler2
            # combined # Rescaler: ActiveReturnCheck/ActRetI_Mon/DiagData_SetEventEntry/Rescaler1 */
         (void) Rte_Call_RP_ActvRetDiagData_Set_ActvRetDiagData(IRV_ActvRetMotTrqSatn_a,
          IRV_ActvRetAbsTorsBarTrqSat, IRV_ActvRetAbsMaxSafeVehSpdSat, IRV_ActvRetAbsSteerAngSat);

         /* # combined # BusOutport: ActiveReturnCheck/ActRetI_Mon/DiagData_SetEventEntry/Set_ActvRe
            tEntry
            # combined # Rescaler: ActiveReturnCheck/ActRetI_Mon/DiagData_SetEventEntry/Rescaler4 */
         (void) Rte_Call_RP_ActvRetSetEveEntry_Set_ActvRetEntry(s_MonitorStatus_ldU8,
          MONID_ACTIVE_RETURN, 0);
         break;
      }
   }
   /* End execution of chart ActiveReturnCheck/ActRetI_Mon/MonitorStateHandler */

   /* TargetLink Outport: ActiveReturnCheck/ActRetI_Mon/ActvRetDi */
   Rte_IrvWrite_ActRetI_Mon_IRV_ActvRetDi(ActvRetDi_ldB);

   /* UnitDelay: ActiveReturnCheck/ActRetI_Mon/Unit Delay */
   *(Rte_Pim_PIM_ActvRetDi()) = ActvRetDi_ldB;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetI_Saturation
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCheck_CODE) ActRetI_Saturation(void)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   IDT_AbsMaxSafeVehSpd AbsMaxSafeVehSpd; /* LSB: 2^-6 OFF: 0 MIN/MAX: 0 .. 500 */
   uint16 AbsSteeringAngle_ldU16; /* 
      Unit: °
      LSB: 0.1 OFF: 0 MIN/MAX: 0 .. 6553.5 */
   uint16 AbsTorsionBarTorque_ldU16; /* 
      Unit: Nm
      LSB: 2^-10 OFF: 0 MIN/MAX: 0 .. 63.9990234375 */
   uint16 ActvRetAbsMaxSafeVehSpdSat_ldU16; /* LSB: 2^-6 OFF: 0 MIN/MAX: 0 .. 1023.984375 */
   uint16 ActvRetAbsSteerAngSat_ldU16; /* LSB: 0.1 OFF: 0 MIN/MAX: 0 .. 6553.5 */
   uint16 ActvRetAbsTorsBarTrqSat_ldU16; /* LSB: 2^-10 OFF: 0 MIN/MAX: 0 .. 63.9990234375 */
   uint16 ActvRetMaxMotTrqMin_ldU16; /* LSB: 2^-10 OFF: 0 MIN/MAX: 0 .. 3 */
   IDT_ActvRetMotTrq4Chk ActvRetMotTrq4Chk_a; /* LSB: 2^-10 OFF: 0 MIN/MAX: -3 .. 3 */
   uint16 MaxMotTrqDepOnSteerAng_Val; /* LSB: 2^-10 OFF: 0 MIN/MAX: 0 .. 3 */
   uint16 MaxMotTrqDepOnVehSpd_Val; /* LSB: 2^-10 OFF: 0 MIN/MAX: 0 .. 3 */
   IDT_SteerAng SteerAng; /* LSB: 0.1 OFF: 0 MIN/MAX: -1000 .. 1000 */
   IDT_TorsBarTrq TorsBarTrq; /* LSB: 2^-10 OFF: 0 MIN/MAX: -25 .. 25 */
   sint16 m_MaxMotorTorque_ldS16; /* LSB: 2^-10 OFF: 0 MIN/MAX: -32 .. 31.9990234375 */

   /* SLLocal: Default storage class for local variables | Width: 8 */
   uint8 MaxTBT4ShtDwn_Val; /* LSB: 2^-4 OFF: 0 MIN/MAX: 0 .. 15 */

   /* TargetLink Inport: ActiveReturnCheck/ActRetI_Satn/AbsMaxSafeVehSpd */
   (void) Rte_Read_RP_VehSpd_AbsMaxSafeVehSpd(&AbsMaxSafeVehSpd);

   /* Switch: ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Switch1
      ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Switch1: Omitted comparison with constant.
      # combined # RelationalOperator: ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Valid_vVehSpI
      _AbsMaxSafeVehSpd/RelationalOp */
   if (AbsMaxSafeVehSpd <= ADT_AbsMaxSafeVehSpd_UpperLimit) {
      /* Switch: ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Switch1 */
      ActvRetAbsMaxSafeVehSpdSat_ldU16 = AbsMaxSafeVehSpd;
   }
   else {
      /* Switch: ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Switch1 */
      ActvRetAbsMaxSafeVehSpdSat_ldU16 = ADT_AbsMaxSafeVehSpd_UpperLimit;
   }

   /* TargetLink Outport: ActiveReturnCheck/ActRetI_Satn/ActvRetAbsMaxSafeVehSpdSat */
   Rte_IrvWrite_ActRetI_Satn_IRV_ActvRetAbsMaxSafeVehSpdSat(ActvRetAbsMaxSafeVehSpdSat_ldU16);

   /* TargetLink Inport: ActiveReturnCheck/ActRetI_Satn/RP_TorsBarTrq */
   (void) Rte_Read_RP_TorsBarTrq_TorsBarTrq(&TorsBarTrq);

   /* Abs: ActiveReturnCheck/ActRetI_Satn/SignalProcessing/AbsTorsionBarTorque */
   if (TorsBarTrq >= 0) {
      AbsTorsionBarTorque_ldU16 = (uint16) TorsBarTrq;
   }
   else {
      AbsTorsionBarTorque_ldU16 = (uint16) (-TorsBarTrq);
   }

   /* Switch: ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Switch2
      ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Switch2: Omitted comparison with constant.
      # combined # RelationalOperator: ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Valid_mApplI_
      TorsionBarTorque/RelationalOp */
   if (((sint16) AbsTorsionBarTorque_ldU16) <= ADT_TorsBarTrq_UpperLimit) {
      /* Switch: ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Switch2 */
      ActvRetAbsTorsBarTrqSat_ldU16 = AbsTorsionBarTorque_ldU16;
   }
   else {
      /* Switch: ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Switch2 */
      ActvRetAbsTorsBarTrqSat_ldU16 = (uint16) ADT_TorsBarTrq_UpperLimit;
   }

   /* TargetLink Outport: ActiveReturnCheck/ActRetI_Satn/ActvRetAbsTorsBarTrqSat */
   Rte_IrvWrite_ActRetI_Satn_IRV_ActvRetAbsTorsBarTrqSat(ActvRetAbsTorsBarTrqSat_ldU16);

   /* TargetLink Inport: ActiveReturnCheck/ActRetI_Satn/SteerAng */
   (void) Rte_Read_RP_SteerAng_SteerAng(&SteerAng);

   /* Abs: ActiveReturnCheck/ActRetI_Satn/SignalProcessing/AbsSteeringAngle */
   if (SteerAng >= 0) {
      AbsSteeringAngle_ldU16 = (uint16) SteerAng;
   }
   else {
      AbsSteeringAngle_ldU16 = (uint16) (-SteerAng);
   }

   /* Switch: ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Switch
      ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Switch: Omitted comparison with constant.
      # combined # RelationalOperator: ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Valid_wApplI_
      SteeringAngle/RelationalOp */
   if (((sint16) AbsSteeringAngle_ldU16) <= ADT_SteerAng_UpperLimit) {
      /* Switch: ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Switch */
      ActvRetAbsSteerAngSat_ldU16 = AbsSteeringAngle_ldU16;
   }
   else {
      /* Switch: ActiveReturnCheck/ActRetI_Satn/SignalProcessing/Switch */
      ActvRetAbsSteerAngSat_ldU16 = 0;
   }

   /* TargetLink Outport: ActiveReturnCheck/ActRetI_Satn/ActvRetAbsSteerAngSat */
   Rte_IrvWrite_ActRetI_Satn_IRV_ActvRetAbsSteerAngSat(ActvRetAbsSteerAngSat_ldU16);

   /* call of function: ActiveReturnCheck/ActRetI_Satn/CalibrationData/SSCP_RP_ActvRetProvParameters
      _Get_ActvRetMaxMotTrqDepOnSteerAng */
   (void)
    Rte_Call_RP_ActvRetProvParameters_Get_ActvRetMaxMotTrqDepOnSteerAng(&MaxMotTrqDepOnSteerAng_Val,
    ActvRetAbsSteerAngSat_ldU16);

   /* call of function: ActiveReturnCheck/ActRetI_Satn/CalibrationData/SSCP_RP_ActvRetProvParameters
      _Get_ActvRetMaxMotTrqDepOnVehSpd */
   (void)
    Rte_Call_RP_ActvRetProvParameters_Get_ActvRetMaxMotTrqDepOnVehSpd(&MaxMotTrqDepOnVehSpd_Val,
    ActvRetAbsMaxSafeVehSpdSat_ldU16);

   /* MinMax: ActiveReturnCheck/ActRetI_Satn/m_MaxMotTrq */
   if (MaxMotTrqDepOnSteerAng_Val < MaxMotTrqDepOnVehSpd_Val) {
      ActvRetMaxMotTrqMin_ldU16 = MaxMotTrqDepOnSteerAng_Val;
   }
   else {
      ActvRetMaxMotTrqMin_ldU16 = MaxMotTrqDepOnVehSpd_Val;
   }

   /* TargetLink Outport: ActiveReturnCheck/ActRetI_Satn/ActvRetMaxMotTrqMin */
   Rte_IrvWrite_ActRetI_Satn_IRV_ActvRetMaxMotTrqMin(ActvRetMaxMotTrqMin_ldU16);

   /* TargetLink Inport: ActiveReturnCheck/ActRetI_Satn/ActvRetMaxTBT4ShutDown */
   (void) Rte_Call_RP_ActvRetProvParameters_Get_ActvRetMaxTBT4ShtDwn(&MaxTBT4ShtDwn_Val);

   /* Switch: ActiveReturnCheck/ActRetI_Satn/m_MaxMotorTorque
      ActiveReturnCheck/ActRetI_Satn/m_MaxMotorTorque: Omitted comparison with constant.
      # combined # RelationalOperator: ActiveReturnCheck/ActRetI_Satn/f_AboveMaxTBT */
   if (((uint16) (ActvRetAbsTorsBarTrqSat_ldU16 >> 6)) >= ((uint16) MaxTBT4ShtDwn_Val)) {
      /* Switch: ActiveReturnCheck/ActRetI_Satn/m_MaxMotorTorque */
      m_MaxMotorTorque_ldS16 = 0;
   }
   else {
      /* Switch: ActiveReturnCheck/ActRetI_Satn/m_MaxMotorTorque */
      m_MaxMotorTorque_ldS16 = (sint16) ActvRetMaxMotTrqMin_ldU16;
   }

   /* TargetLink Inport: ActiveReturnCheck/ActRetI_Satn/RP_ActvRetMotTrq4Chk */
   (void) Rte_Read_RP_ActvRetMotTrq4Chk_ActvRetMotTrq4Chk(&ActvRetMotTrq4Chk_a);
   if (ActvRetMotTrq4Chk_a > m_MaxMotorTorque_ldS16) {
      /* TargetLink Outport: ActiveReturnCheck/ActRetI_Satn/ActvRetMotTrqSatn
         # combined # Merge: ActiveReturnCheck/ActRetI_Satn/Sat_mActRet_MotTrqSaturated/Merge
         update of variable(s) associated with ActiveReturnCheck/ActRetI_Satn/Sat_mActRet_MotTrqSatu
         rated/upperLimExceeded/In1 */
      Rte_IrvWrite_ActRetI_Satn_IRV_ActvRetMotTrqSatn(m_MaxMotorTorque_ldS16);
   }
   else {
      /* # combined # Gain: ActiveReturnCheck/ActRetI_Satn/Sat_mActRet_MotTrqSaturated/Gain */
      if (ActvRetMotTrq4Chk_a < ((sint16) (-m_MaxMotorTorque_ldS16))) {
         /* TargetLink Outport: ActiveReturnCheck/ActRetI_Satn/ActvRetMotTrqSatn
            # combined # Merge: ActiveReturnCheck/ActRetI_Satn/Sat_mActRet_MotTrqSaturated/Merge
            update of variable(s) associated with ActiveReturnCheck/ActRetI_Satn/Sat_mActRet_MotTrqS
            aturated/lowerLimExceeded/mActRet_MotTrqSaturated_negLim_in
            # combined # Gain: ActiveReturnCheck/ActRetI_Satn/Sat_mActRet_MotTrqSaturated/Gain */
         Rte_IrvWrite_ActRetI_Satn_IRV_ActvRetMotTrqSatn((sint16) (-m_MaxMotorTorque_ldS16));
      }
      else {
         /* TargetLink Outport: ActiveReturnCheck/ActRetI_Satn/ActvRetMotTrqSatn
            # combined # Merge: ActiveReturnCheck/ActRetI_Satn/Sat_mActRet_MotTrqSaturated/Merge
            update of variable(s) associated with ActiveReturnCheck/ActRetI_Satn/Sat_mActRet_MotTrqS
            aturated/withinLimits/mActRetI_MotTrq4Check_in */
         Rte_IrvWrite_ActRetI_Satn_IRV_ActvRetMotTrqSatn(ActvRetMotTrq4Chk_a);
      }
   }
}

/* end of memory section 'CODE' */
#define ActiveReturnCheck_STOP_SEC_CODE
#include "ActiveReturnCheck_MemMap.h"

/*------------------------------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/
#endif /* IACTRET_CHECK_GG_C */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/

