/**************************************************************************************************\
 *** Copyright (c) Robert Bosch Automotive Steering GmbH, Germany
 *** All rights reserved
 ***
 *** Generated by: Raghul Gnanaseelan (MS/EPP10-AS)
 ***
 *** Generated with:
 *** MathWorks MATLAB                            9.9 (R2020b)
 *** dSPACE TargetLink Production Code Generator 5.1p2
 *** AS --- MBSD environment                     R2301-hotfix2
 *** AS --- DataDictionary structure level       5
 *** AS --- MBSD repository
 *** AS ---    sourcecode02.de.bosch.com/projects/MBSD/repos/mbsd/browse?at=537712056067caf70571199527af8b914a901532
 *** AS --- Train repository
 *** AS ---    sourcecode02.de.bosch.com/projects/ASMPAPP/repos/app-train/browse?at=7c6ea450cb8147c9e46507ef1e35a1d06c672957
\**************************************************************************************************/
/**************************************************************************************************\
 *** 
 *** Simulink model       : ActiveReturnCdp_sm
 *** TargetLink subsystem : ActiveReturnCdp_sm/ActiveReturnCdp
 *** Codefile             : ActiveReturnCdp_lut_gg.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2023-05-11 19:12:29
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Classic AUTOSAR
 *** AUTOSAR version                          : 4.3.0
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : AvoidPotentiallyUndefinedShiftsBasedOnWorstCaseRange
 s
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : disabled
 *** State activity encoding limit            : 1
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 100
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.1\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.1\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS         CORRESPONDING SIMULINK SUBSYSTEM
 *** SARC1          ActiveReturnCdp
 *** SARC2          ActiveReturnCdp/ActRetCdp_Prov_FilFac
 *** SARC3          ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq
 *** SARC4          ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac
 *** SARC5          ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng
 *** SARC6          ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd
 *** SARC7          ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn
 *** SARC8          ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain
 *** SARC9          ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd
 *** SARC10         ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr
 *** SARC11         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp
 *** SARC12         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact
 *** SARC13         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr
 *** SARC14         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld
 *** SARC15         ActiveReturnCdp/Additional_Design_Information
 *** SARC16         ActiveReturnCdp/ActRetCdp_Prov_FilFac/ActRetCdp_Prov_FilFacA
 *** SARC17         ActiveReturnCdp/ActRetCdp_Prov_FilFac/ActRetCdp_Prov_FilFacB
 *** SARC18         ActiveReturnCdp/ActRetCdp_Prov_FilFac/ActRetCdp_Prov_FilFacC
 *** SARC19         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/ActRetCdp_Prov_MaxMotTrqA
 *** SARC20         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/ActRetCdp_Prov_MaxMotTrqB
 *** SARC21         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/ActRetCdp_Prov_MaxMotTrqC
 *** SARC22         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac/ActRetCdp_Prov_MaxMotTrqAftLo
 ***                adFacA
 *** SARC23         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac/ActRetCdp_Prov_MaxMotTrqAftLo
 ***                adFacB
 *** SARC24         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac/ActRetCdp_Prov_MaxMotTrqAftLo
 ***                adFacC
 *** SARC25         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRetCdp_Prov_MaxMotTrqDe
 ***                pOnSteerAngA
 *** SARC26         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRetCdp_Prov_MaxMotTrqDe
 ***                pOnSteerAngB
 *** SARC27         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRetCdp_Prov_MaxMotTrqDe
 ***                pOnSteerAngC
 *** SARC28         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRetCdp_Prov_MaxMotTrqDe
 ***                pOnSteerAngA/MaxMotTrqDepOnSteerAngA
 *** SARC29         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRetCdp_Prov_MaxMotTrqDe
 ***                pOnSteerAngB/MaxMotTrqDepOnSteerAngB
 *** SARC30         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRetCdp_Prov_MaxMotTrqDe
 ***                pOnSteerAngC/MaxMotTrqDepOnSteerAngC
 *** SARC31         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCdp_Prov_MaxMotTrqDepO
 ***                nVehSpdA
 *** SARC32         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCdp_Prov_MaxMotTrqDepO
 ***                nVehSpdB
 *** SARC33         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCdp_Prov_MaxMotTrqDepO
 ***                nVehSpdC
 *** SARC34         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCdp_Prov_MaxMotTrqDepO
 ***                nVehSpdA/MaxMotTrqDepOnVehSpdA
 *** SARC35         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCdp_Prov_MaxMotTrqDepO
 ***                nVehSpdB/MaxMotTrqDepOnVehSpdB
 *** SARC36         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCdp_Prov_MaxMotTrqDepO
 ***                nVehSpdC/MaxMotTrqDepOnVehSpdC
 *** SARC37         ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/ActRetCdp_Prov_MaxTBT4ShtDwnA
 *** SARC38         ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/ActRetCdp_Prov_MaxTBT4ShtDwnB
 *** SARC39         ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/ActRetCdp_Prov_MaxTBT4ShtDwnC
 *** SARC40         ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_MotTrqGainA
 *** SARC41         ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_MotTrqGainB
 *** SARC42         ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_MotTrqGainC
 *** SARC43         ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_MotTrqGainA/MotTrqGainA
 *** SARC44         ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_MotTrqGainB/MotTrqGainB
 *** SARC45         ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_MotTrqGainC/MotTrqGainC
 *** SARC46         ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdA
 *** SARC47         ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdB
 *** SARC48         ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdC
 *** SARC49         ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdA/NomSteerS
 ***                pdA
 *** SARC50         ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdB/NomSteerS
 ***                pdB
 *** SARC51         ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdC/NomSteerS
 ***                pdC
 *** SARC52         ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFactDepO
 ***                nDrvrA
 *** SARC53         ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFactDepO
 ***                nDrvrB
 *** SARC54         ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFactDepO
 ***                nDrvrC
 *** SARC55         ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFactDepO
 ***                nDrvrA/RetTrqFactDepOnDrvrA
 *** SARC56         ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFactDepO
 ***                nDrvrB/RetTrqFactDepOnDrvrB
 *** SARC57         ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFactDepO
 ***                nDrvrC/RetTrqFactDepOnDrvrC
 *** SARC58         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/ActRetCdp_Prov_SteerSpdAmpA
 *** SARC59         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/ActRetCdp_Prov_SteerSpdAmpB
 *** SARC60         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/ActRetCdp_Prov_SteerSpdAmpC
 *** SARC61         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/ActRetCdp_Prov_SteerSpdFactA
 *** SARC62         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/ActRetCdp_Prov_SteerSpdFactB
 *** SARC63         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/ActRetCdp_Prov_SteerSpdFactC
 *** SARC64         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSpdFact
 ***                DepOnDrvrA
 *** SARC65         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSpdFact
 ***                DepOnDrvrB
 *** SARC66         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSpdFact
 ***                DepOnDrvrC
 *** SARC67         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSpdFact
 ***                DepOnDrvrA/xActRet_SteerSpeedFactDepOnDriverA
 *** SARC68         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSpdFact
 ***                DepOnDrvrB/SteerSpdFactDepOnDrvrB
 *** SARC69         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSpdFact
 ***                DepOnDrvrC/SteerSpdFactDepOnDrvrC
 *** SARC70         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld/ActRetCdp_Prov_SteerSpdGradA
 ***                ftInvldA
 *** SARC71         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld/ActRetCdp_Prov_SteerSpdGradA
 ***                ftInvldB
 *** SARC72         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld/ActRetCdp_Prov_SteerSpdGradA
 ***                ftInvldC
 *** SARC73         ActiveReturnCdp/Additional_Design_Information/Appendix
 *** SARC74         ActiveReturnCdp/Additional_Design_Information/Calibration_Data
 *** SARC75         ActiveReturnCdp/Additional_Design_Information/Configuration_Data
 *** SARC76         ActiveReturnCdp/Additional_Design_Information/Dependencies
 *** SARC77         ActiveReturnCdp/Additional_Design_Information/Integration_Hints
 *** SARC78         ActiveReturnCdp/Additional_Design_Information/Interfaces
 *** SARC79         ActiveReturnCdp/Additional_Design_Information/Internals
 *** SARC80         ActiveReturnCdp/Additional_Design_Information/Safety_Concept
 *** SARC81         ActiveReturnCdp/Additional_Design_Information/Short_Description
 *** SARC82         ActiveReturnCdp/Additional_Design_Information/Calibration_Data/imageFunctionalIn
 ***                terfaces
 *** SARC83         ActiveReturnCdp/Additional_Design_Information/Integration_Hints/imageFunctionalI
 ***                nterfaces
 *** SARC84         ActiveReturnCdp/Additional_Design_Information/Interfaces/imageDataInterfaces
 *** SARC85         ActiveReturnCdp/Additional_Design_Information/Interfaces/imageFunctionalInterfac
 ***                es
 *** SARC86         ActiveReturnCdp/Additional_Design_Information/Internals/imageDataInterfaces
 *** SARC87         ActiveReturnCdp/Additional_Design_Information/Internals/imageFunctionalInterface
 ***                s
 *** 
 *** SUBSYS         CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE        CORRESPONDING STATEFLOW NODE                    DESCRIPTION
 *** CARC0          ActiveReturnCdp_sm                              
 *** CARC1          ActiveReturnCdp/Scheduler                       
 *** 
 *** TargetLink version      : 5.1p2 from 24-Jan-2022
 *** Code generator version  : Build Id 5.1.0.30 from 2022-01-24 15:16:38
\**************************************************************************************************/

#ifndef ACTIVERETURNCDP_LUT_GG_C
#define ACTIVERETURNCDP_LUT_GG_C

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "ActiveReturnCdp_lut_gg.h"

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Tab1DIntp2I1T65_ARC
 *** 
 ***  DESCRIPTION:
 ***      Automatic generated function for Interpolation using PreLook-Up blocks.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const uint16 *     z_table             pointer to table vector
 ***      uint8              irx                 1. table input index
 ***      uint16             fractionX           1. table input fraction
 ***
 ***  RETURNS:
 ***      uint16
 ***
 ***  SETTINGS:
 ***      Number of table dimensions.........: 1
 ***      Interpolation......................: on
 ***      Distances fit into given bitlengths: no
 ***
\**************************************************************************************************/
uint16 Tab1DIntp2I1T65_ARC(const uint16 * z_table, uint8 irx, uint16 fractionX)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   uint16 Aux_ldU16;
   uint16 Aux_ldU16_a;

   z_table += irx;
   Aux_ldU16 = *(z_table++);
   if (fractionX != 0) {
      Aux_ldU16_a = *z_table;
      if (Aux_ldU16 <= Aux_ldU16_a) {
         Aux_ldU16 += ((uint16) ((((uint32) (uint16) (Aux_ldU16_a - Aux_ldU16)) * ((uint32)
          fractionX)) >> 16));
      }
      else {
         Aux_ldU16 -= ((uint16) ((((uint32) (uint16) (Aux_ldU16 - Aux_ldU16_a)) * ((uint32)
          fractionX)) >> 16));
      }
   }
   return Aux_ldU16;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Tab2DIntp2I1T33281_ARC
 *** 
 ***  DESCRIPTION:
 ***      Automatic generated function for Interpolation using PreLook-Up blocks.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const uint16 *     z_table             pointer to table vector
 ***      uint8              N                   number of values in y-axis vector
 ***      uint8              irx                 1. table input index
 ***      uint16             fractionX           1. table input fraction
 ***      uint8              iry                 2. table input index
 ***      uint16             fractionY           2. table input fraction
 ***
 ***  RETURNS:
 ***      uint16
 ***
 ***  SETTINGS:
 ***      Number of table dimensions.........: 2
 ***      Interpolation......................: on
 ***      Distances fit into given bitlengths: no
 ***
\**************************************************************************************************/
uint16 Tab2DIntp2I1T33281_ARC(const uint16 * z_table, uint8 N, uint8 irx, uint16 fractionX, uint8
  iry, uint16 fractionY)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   uint16 Aux_ldU16;
   uint16 Aux_ldU16_a;
   uint16 Aux_ldU16_b;

   z_table += ((uint16) (((uint16) (((uint16) irx) * ((uint16) N))) + ((uint16) iry)));
   Aux_ldU16 = z_table[0];
   if (fractionY == 0) {
      if (fractionX == 0) {
         return Aux_ldU16;
      }
      Aux_ldU16_a = z_table[N];
   }
   else {
      /* 1. Y-Interpolation. */
      Aux_ldU16_b = z_table[1];
      if (Aux_ldU16 <= Aux_ldU16_b) {
         Aux_ldU16 += ((uint16) ((((uint32) (uint16) (Aux_ldU16_b - Aux_ldU16)) * ((uint32)
          fractionY)) >> 16));
      }
      else {
         Aux_ldU16 -= ((uint16) ((((uint32) (uint16) (Aux_ldU16 - Aux_ldU16_b)) * ((uint32)
          fractionY)) >> 16));
      }
      if (fractionX == 0) {
         return Aux_ldU16;
      }
      z_table += N;

      /* 2. Y-Interpolation. */
      Aux_ldU16_a = *(z_table++);

      /* X-Interpolation. */
      Aux_ldU16_b = z_table[0];
      if (Aux_ldU16_a <= Aux_ldU16_b) {
         Aux_ldU16_a += ((uint16) ((((uint32) (uint16) (Aux_ldU16_b - Aux_ldU16_a)) * ((uint32)
          fractionY)) >> 16));
      }
      else {
         Aux_ldU16_a -= ((uint16) ((((uint32) (uint16) (Aux_ldU16_a - Aux_ldU16_b)) * ((uint32)
          fractionY)) >> 16));
      }
   }
   if (fractionX != 0) {
      if (Aux_ldU16 <= Aux_ldU16_a) {
         Aux_ldU16 += ((uint16) ((((uint32) (uint16) (Aux_ldU16_a - Aux_ldU16)) * ((uint32)
          fractionX)) >> 16));
      }
      else {
         Aux_ldU16 -= ((uint16) ((((uint32) (uint16) (Aux_ldU16 - Aux_ldU16_a)) * ((uint32)
          fractionX)) >> 16));
      }
   }
   return Aux_ldU16;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      TabIdxS48T513_ARC
 *** 
 ***  DESCRIPTION:
 ***      Automatic generated function for PreLook-Up Index Search blocks.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const uint16 *     x_table             pointer to x-axis vector
 ***      uint8              N                   number of values in x-axis vector
 ***      uint16             x                   table input
 ***      uint8 *            irx                 table output
 ***      uint16 *           fraction            table output
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***      Search algorithm...................: ascending linear search.
 ***      Output configuration...............: output index and fraction, two variables
 ***
\**************************************************************************************************/
void TabIdxS48T513_ARC(const uint16 * x_table, uint8 N, uint16 x, uint8 * irx, uint16 * fraction)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   uint8 Aux_ldU8;

   /* Saturation. */
   if (x <= *x_table) {
      *irx = 0;
      *fraction = 0;
   }
   else {
      if (x >= x_table[N - 1]) {
         *irx = N - 1;
         *fraction = 0;
      }
      else {
         Aux_ldU8 = 0;

         /* Linear search, start low. */
         x_table++;
         while (x >= *(x_table++)) {
            Aux_ldU8++;
         }
         x_table -= 2;
         *irx = Aux_ldU8;
         *fraction = (uint16) (((uint32) (((uint32) (uint16) (x - x_table[0])) << 16)) / ((uint16)
          (x_table[1] - x_table[0])));
      }
   }
}

/*------------------------------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/
#endif /* ACTIVERETURNCDP_LUT_GG_C */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/

