/**************************************************************************************************\
 *** Copyright (c) Robert Bosch Automotive Steering GmbH, Germany
 *** All rights reserved
 ***
 *** Generated by: Raghul Gnanaseelan (MS/EPP10-AS)
 ***
 *** Generated with:
 *** MathWorks MATLAB                            9.9 (R2020b)
 *** dSPACE TargetLink Production Code Generator 5.1p2
 *** AS --- MBSD environment                     R2301-hotfix2
 *** AS --- DataDictionary structure level       5
 *** AS --- MBSD repository
 *** AS ---    sourcecode02.de.bosch.com/projects/MBSD/repos/mbsd/browse?at=537712056067caf70571199527af8b914a901532
 *** AS --- Train repository
 *** AS ---    sourcecode02.de.bosch.com/projects/ASMPAPP/repos/app-train/browse?at=7c6ea450cb8147c9e46507ef1e35a1d06c672957
\**************************************************************************************************/
/**************************************************************************************************\
 *** 
 *** Simulink model       : ActiveReturnCdp_sm
 *** TargetLink subsystem : ActiveReturnCdp_sm/ActiveReturnCdp
 *** Codefile             : ActiveReturnCdp_lut_gg.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2023-05-11 19:12:29
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Classic AUTOSAR
 *** AUTOSAR version                          : 4.3.0
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : AvoidPotentiallyUndefinedShiftsBasedOnWorstCaseRange
 s
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : disabled
 *** State activity encoding limit            : 1
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 100
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.1\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.1\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 5.1p2 from 24-Jan-2022
 *** Code generator version  : Build Id 5.1.0.30 from 2022-01-24 15:16:38
\**************************************************************************************************/

#ifndef ACTIVERETURNCDP_LUT_GG_H
#define ACTIVERETURNCDP_LUT_GG_H

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "Rte_Type.h"

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   GlobalLookup1D_ARC: Derived TL_CG default function class.
\**************************************************************************************************/
extern uint16 Tab1DIntp2I1T65_ARC(const uint16 * z_table, uint8 irx, uint16 fractionX);
extern uint16 Tab2DIntp2I1T33281_ARC(const uint16 * z_table, uint8 N, uint8 irx, uint16 fractionX,
    uint8 iry, uint16 fractionY);

/**************************************************************************************************\
   GlobalLookup1D_ARC: Derived TL_CG default function class.
\**************************************************************************************************/
extern void TabIdxS48T513_ARC(const uint16 * x_table, uint8 N, uint16 x, uint8 * irx, uint16 *
    fraction);

#endif /* ACTIVERETURNCDP_LUT_GG_H */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/

