/**************************************************************************************************\
 *** Copyright (c) Robert Bosch Automotive Steering GmbH, Germany
 *** All rights reserved
 ***
 *** Generated by: Raghul Gnanaseelan (MS/EPP10-AS)
 ***
 *** Generated with:
 *** MathWorks MATLAB                            9.9 (R2020b)
 *** dSPACE TargetLink Production Code Generator 5.1p2
 *** AS --- MBSD environment                     R2301-hotfix2
 *** AS --- DataDictionary structure level       5
 *** AS --- MBSD repository
 *** AS ---    sourcecode02.de.bosch.com/projects/MBSD/repos/mbsd/browse?at=537712056067caf70571199527af8b914a901532
 *** AS --- Train repository
 *** AS ---    sourcecode02.de.bosch.com/projects/ASMPAPP/repos/app-train/browse?at=7c6ea450cb8147c9e46507ef1e35a1d06c672957
\**************************************************************************************************/
/**************************************************************************************************\
 *** 
 *** Simulink model       : ActiveReturnCdp_sm
 *** TargetLink subsystem : ActiveReturnCdp_sm/ActiveReturnCdp
 *** Codefile             : IActiveReturnCdp_gg.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2023-05-11 19:12:29
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Classic AUTOSAR
 *** AUTOSAR version                          : 4.3.0
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : AvoidPotentiallyUndefinedShiftsBasedOnWorstCaseRange
 s
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : disabled
 *** State activity encoding limit            : 1
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 100
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.1\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.1\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS         CORRESPONDING SIMULINK SUBSYSTEM
 *** SARC1          ActiveReturnCdp
 *** SARC2          ActiveReturnCdp/ActRetCdp_Prov_FilFac
 *** SARC3          ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq
 *** SARC4          ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac
 *** SARC5          ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng
 *** SARC6          ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd
 *** SARC7          ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn
 *** SARC8          ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain
 *** SARC9          ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd
 *** SARC10         ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr
 *** SARC11         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp
 *** SARC12         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact
 *** SARC13         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr
 *** SARC14         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld
 *** SARC15         ActiveReturnCdp/Additional_Design_Information
 *** SARC16         ActiveReturnCdp/ActRetCdp_Prov_FilFac/ActRetCdp_Prov_FilFacA
 *** SARC17         ActiveReturnCdp/ActRetCdp_Prov_FilFac/ActRetCdp_Prov_FilFacB
 *** SARC18         ActiveReturnCdp/ActRetCdp_Prov_FilFac/ActRetCdp_Prov_FilFacC
 *** SARC19         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/ActRetCdp_Prov_MaxMotTrqA
 *** SARC20         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/ActRetCdp_Prov_MaxMotTrqB
 *** SARC21         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/ActRetCdp_Prov_MaxMotTrqC
 *** SARC22         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac/ActRetCdp_Prov_MaxMotTrqAftLo
 ***                adFacA
 *** SARC23         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac/ActRetCdp_Prov_MaxMotTrqAftLo
 ***                adFacB
 *** SARC24         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac/ActRetCdp_Prov_MaxMotTrqAftLo
 ***                adFacC
 *** SARC25         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRetCdp_Prov_MaxMotTrqDe
 ***                pOnSteerAngA
 *** SARC26         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRetCdp_Prov_MaxMotTrqDe
 ***                pOnSteerAngB
 *** SARC27         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRetCdp_Prov_MaxMotTrqDe
 ***                pOnSteerAngC
 *** SARC28         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRetCdp_Prov_MaxMotTrqDe
 ***                pOnSteerAngA/MaxMotTrqDepOnSteerAngA
 *** SARC29         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRetCdp_Prov_MaxMotTrqDe
 ***                pOnSteerAngB/MaxMotTrqDepOnSteerAngB
 *** SARC30         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRetCdp_Prov_MaxMotTrqDe
 ***                pOnSteerAngC/MaxMotTrqDepOnSteerAngC
 *** SARC31         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCdp_Prov_MaxMotTrqDepO
 ***                nVehSpdA
 *** SARC32         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCdp_Prov_MaxMotTrqDepO
 ***                nVehSpdB
 *** SARC33         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCdp_Prov_MaxMotTrqDepO
 ***                nVehSpdC
 *** SARC34         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCdp_Prov_MaxMotTrqDepO
 ***                nVehSpdA/MaxMotTrqDepOnVehSpdA
 *** SARC35         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCdp_Prov_MaxMotTrqDepO
 ***                nVehSpdB/MaxMotTrqDepOnVehSpdB
 *** SARC36         ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCdp_Prov_MaxMotTrqDepO
 ***                nVehSpdC/MaxMotTrqDepOnVehSpdC
 *** SARC37         ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/ActRetCdp_Prov_MaxTBT4ShtDwnA
 *** SARC38         ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/ActRetCdp_Prov_MaxTBT4ShtDwnB
 *** SARC39         ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/ActRetCdp_Prov_MaxTBT4ShtDwnC
 *** SARC40         ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_MotTrqGainA
 *** SARC41         ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_MotTrqGainB
 *** SARC42         ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_MotTrqGainC
 *** SARC43         ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_MotTrqGainA/MotTrqGainA
 *** SARC44         ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_MotTrqGainB/MotTrqGainB
 *** SARC45         ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_MotTrqGainC/MotTrqGainC
 *** SARC46         ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdA
 *** SARC47         ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdB
 *** SARC48         ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdC
 *** SARC49         ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdA/NomSteerS
 ***                pdA
 *** SARC50         ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdB/NomSteerS
 ***                pdB
 *** SARC51         ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdC/NomSteerS
 ***                pdC
 *** SARC52         ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFactDepO
 ***                nDrvrA
 *** SARC53         ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFactDepO
 ***                nDrvrB
 *** SARC54         ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFactDepO
 ***                nDrvrC
 *** SARC55         ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFactDepO
 ***                nDrvrA/RetTrqFactDepOnDrvrA
 *** SARC56         ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFactDepO
 ***                nDrvrB/RetTrqFactDepOnDrvrB
 *** SARC57         ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFactDepO
 ***                nDrvrC/RetTrqFactDepOnDrvrC
 *** SARC58         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/ActRetCdp_Prov_SteerSpdAmpA
 *** SARC59         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/ActRetCdp_Prov_SteerSpdAmpB
 *** SARC60         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/ActRetCdp_Prov_SteerSpdAmpC
 *** SARC61         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/ActRetCdp_Prov_SteerSpdFactA
 *** SARC62         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/ActRetCdp_Prov_SteerSpdFactB
 *** SARC63         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/ActRetCdp_Prov_SteerSpdFactC
 *** SARC64         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSpdFact
 ***                DepOnDrvrA
 *** SARC65         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSpdFact
 ***                DepOnDrvrB
 *** SARC66         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSpdFact
 ***                DepOnDrvrC
 *** SARC67         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSpdFact
 ***                DepOnDrvrA/xActRet_SteerSpeedFactDepOnDriverA
 *** SARC68         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSpdFact
 ***                DepOnDrvrB/SteerSpdFactDepOnDrvrB
 *** SARC69         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSpdFact
 ***                DepOnDrvrC/SteerSpdFactDepOnDrvrC
 *** SARC70         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld/ActRetCdp_Prov_SteerSpdGradA
 ***                ftInvldA
 *** SARC71         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld/ActRetCdp_Prov_SteerSpdGradA
 ***                ftInvldB
 *** SARC72         ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld/ActRetCdp_Prov_SteerSpdGradA
 ***                ftInvldC
 *** SARC73         ActiveReturnCdp/Additional_Design_Information/Appendix
 *** SARC74         ActiveReturnCdp/Additional_Design_Information/Calibration_Data
 *** SARC75         ActiveReturnCdp/Additional_Design_Information/Configuration_Data
 *** SARC76         ActiveReturnCdp/Additional_Design_Information/Dependencies
 *** SARC77         ActiveReturnCdp/Additional_Design_Information/Integration_Hints
 *** SARC78         ActiveReturnCdp/Additional_Design_Information/Interfaces
 *** SARC79         ActiveReturnCdp/Additional_Design_Information/Internals
 *** SARC80         ActiveReturnCdp/Additional_Design_Information/Safety_Concept
 *** SARC81         ActiveReturnCdp/Additional_Design_Information/Short_Description
 *** SARC82         ActiveReturnCdp/Additional_Design_Information/Calibration_Data/imageFunctionalIn
 ***                terfaces
 *** SARC83         ActiveReturnCdp/Additional_Design_Information/Integration_Hints/imageFunctionalI
 ***                nterfaces
 *** SARC84         ActiveReturnCdp/Additional_Design_Information/Interfaces/imageDataInterfaces
 *** SARC85         ActiveReturnCdp/Additional_Design_Information/Interfaces/imageFunctionalInterfac
 ***                es
 *** SARC86         ActiveReturnCdp/Additional_Design_Information/Internals/imageDataInterfaces
 *** SARC87         ActiveReturnCdp/Additional_Design_Information/Internals/imageFunctionalInterface
 ***                s
 *** 
 *** SUBSYS         CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE        CORRESPONDING STATEFLOW NODE                    DESCRIPTION
 *** CARC0          ActiveReturnCdp_sm                              
 *** CARC1          ActiveReturnCdp/Scheduler                       
 *** 
 *** TargetLink version      : 5.1p2 from 24-Jan-2022
 *** Code generator version  : Build Id 5.1.0.30 from 2022-01-24 15:16:38
\**************************************************************************************************/

#ifndef IACTIVERETURNCDP_GG_C
#define IACTIVERETURNCDP_GG_C

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "Rte_ActiveReturnCdp.h"
#include "IActiveReturnCdp_gg.h"
#include "ActiveReturnCdp_lut_gg.h"

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/* start of memory section 'CODE' */
#define ActiveReturnCdp_START_SEC_CODE
#include "ActiveReturnCdp_MemMap.h"
/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetCdp_ProvideFilterFactor
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCdp_CODE) ActRetCdp_ProvideFilterFactor(P2VAR(uint16, AUTOMATIC,
  RTE_APPL_DATA) FilFac_Val)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   IDT_ActChar ActChar; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 2 */

   /* TargetLink inport: ActiveReturnCdp/ActRetCdp_Prov_FilFac/ActChar */
   Rte_Read_RP_ActChar_ActChar(&ActChar);

   /* SwitchCase: ActiveReturnCdp/ActRetCdp_Prov_FilFac/Switch Case */
   switch (ActChar) {
      case 1: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_FilFac/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_FilFac/ActRetCdp_Pr
            ov_FilFacB/FilFacB
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_FilFac/FilFac_Val */
         *FilFac_Val = Rte_CData_FilFacB();
         break;
      }
      case 2: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_FilFac/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_FilFac/ActRetCdp_Pr
            ov_FilFacC/FilFacC
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_FilFac/FilFac_Val */
         *FilFac_Val = Rte_CData_FilFacC();
         break;
      }
      default: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_FilFac/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_FilFac/ActRetCdp_Pr
            ov_FilFacA/FilFacA
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_FilFac/FilFac_Val */
         *FilFac_Val = Rte_CData_FilFacA();
         break;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetCdp_ProvideMaxMotorTorque
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCdp_CODE) ActRetCdp_ProvideMaxMotorTorque(P2VAR(uint8, AUTOMATIC,
  RTE_APPL_DATA) MaxMotTrq_Val)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   IDT_ActChar ActChar; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 2 */

   /* TargetLink inport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/ActChar */
   Rte_Read_RP_ActChar_ActChar(&ActChar);

   /* SwitchCase: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/Switch Case */
   switch (ActChar) {
      case 1: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/ActRetCdp
            _Prov_MaxMotTrqB/MaxMotTrqB
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/MaxMotTrq_Val
             */
         *MaxMotTrq_Val = Rte_CData_MaxMotTrqB();
         break;
      }
      case 2: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/ActRetCdp
            _Prov_MaxMotTrqC/MaxMotTrqC
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/MaxMotTrq_Val
             */
         *MaxMotTrq_Val = Rte_CData_MaxMotTrqC();
         break;
      }
      default: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/ActRetCdp
            _Prov_MaxMotTrqA/MaxMotTrqA
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrq/MaxMotTrq_Val
             */
         *MaxMotTrq_Val = Rte_CData_MaxMotTrqA();
         break;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetCdp_ProvideMaxMotorTorqueDepOnSteeringAngle
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCdp_CODE) ActRetCdp_ProvideMaxMotorTorqueDepOnSteeringAngle(P2VAR(uint16,
  AUTOMATIC, RTE_APPL_DATA) MaxMotTrqDepOnSteerAng_Val, IDT_AbsSteerAng AbsSteerAng)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   IDT_ActChar ActChar; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 2 */

   /* TargetLink inport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActChar */
   Rte_Read_RP_ActChar_ActChar(&ActChar);

   /* SwitchCase: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/Switch Case */
   switch (ActChar) {
      case 1: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_mActRet_MaxMotorTorqueDepOnSteeringAngleB_XAU16_AxisX_ldU16; /* LSB: 2^-1
         6 OFF: 0 MIN/MAX: 0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_mActRet_MaxMotorTorqueDepOnSteeringAngleB_XAU16_AxisX_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRetCdp_Prov_MaxMot
            TrqDepOnSteerAngB/MaxMotTrqDepOnSteerAngB/MaxMotTrqDepOnSteerAngB_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMot
            TrqDepOnSteerAng/AbsSteerAng */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_MaxMotTrqDepOnSteerAngB_AxisX()[0]), 5,
          AbsSteerAng, &y_index_mActRet_MaxMotorTorqueDepOnSteeringAngleB_XAU16_AxisX_ldU8,
          &x_fraction_mActRet_MaxMotorTorqueDepOnSteeringAngleB_XAU16_AxisX_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteer
            Ang/ActRetCdp_Prov_MaxMotTrqDepOnSteerAngB/MaxMotTrqDepOnSteerAngB/MaxMotTrqDepOnSteerAn
            g
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/M
            axMotTrqDepOnSteerAng_Val
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRet
            Cdp_Prov_MaxMotTrqDepOnSteerAngB/MaxMotTrqDepOnSteerAngB/MaxMotTrqDepOnSteerAng */
         *MaxMotTrqDepOnSteerAng_Val = Tab1DIntp2I1T65_ARC((const uint16 *)
          &(Rte_CData_MaxMotTrqDepOnSteerAngB()[0]),
          y_index_mActRet_MaxMotorTorqueDepOnSteeringAngleB_XAU16_AxisX_ldU8,
          x_fraction_mActRet_MaxMotorTorqueDepOnSteeringAngleB_XAU16_AxisX_ldU16);
         break;
      }
      case 2: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_mActRet_MaxMotorTorqueDepOnSteeringAngleC_XAU16_AxisX_ldU16; /* LSB: 2^-1
         6 OFF: 0 MIN/MAX: 0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_mActRet_MaxMotorTorqueDepOnSteeringAngleC_XAU16_AxisX_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRetCdp_Prov_MaxMot
            TrqDepOnSteerAngC/MaxMotTrqDepOnSteerAngC/MaxMotTrqDepOnSteerAngC_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMot
            TrqDepOnSteerAng/AbsSteerAng */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_MaxMotTrqDepOnSteerAngC_AxisX()[0]), 5,
          AbsSteerAng, &y_index_mActRet_MaxMotorTorqueDepOnSteeringAngleC_XAU16_AxisX_ldU8,
          &x_fraction_mActRet_MaxMotorTorqueDepOnSteeringAngleC_XAU16_AxisX_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteer
            Ang/ActRetCdp_Prov_MaxMotTrqDepOnSteerAngC/MaxMotTrqDepOnSteerAngC/MaxMotTrqDepOnSteerAn
            g
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/M
            axMotTrqDepOnSteerAng_Val
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRet
            Cdp_Prov_MaxMotTrqDepOnSteerAngC/MaxMotTrqDepOnSteerAngC/MaxMotTrqDepOnSteerAng */
         *MaxMotTrqDepOnSteerAng_Val = Tab1DIntp2I1T65_ARC((const uint16 *)
          &(Rte_CData_MaxMotTrqDepOnSteerAngC()[0]),
          y_index_mActRet_MaxMotorTorqueDepOnSteeringAngleC_XAU16_AxisX_ldU8,
          x_fraction_mActRet_MaxMotorTorqueDepOnSteeringAngleC_XAU16_AxisX_ldU16);
         break;
      }
      default: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_mActRet_MaxMotorTorqueDepOnSteeringAngleA_XAU16_AxisX_ldU16; /* LSB: 2^-1
         6 OFF: 0 MIN/MAX: 0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_mActRet_MaxMotorTorqueDepOnSteeringAngleA_XAU16_AxisX_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRetCdp_Prov_MaxMot
            TrqDepOnSteerAngA/MaxMotTrqDepOnSteerAngA/MaxMotTrqDepOnSteerAng_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMot
            TrqDepOnSteerAng/AbsSteerAng */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_MaxMotTrqDepOnSteerAngA_AxisX()[0]), 5,
          AbsSteerAng, &y_index_mActRet_MaxMotorTorqueDepOnSteeringAngleA_XAU16_AxisX_ldU8,
          &x_fraction_mActRet_MaxMotorTorqueDepOnSteeringAngleA_XAU16_AxisX_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteer
            Ang/ActRetCdp_Prov_MaxMotTrqDepOnSteerAngA/MaxMotTrqDepOnSteerAngA/MaxMotTrqDepOnSteerAn
            g
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/M
            axMotTrqDepOnSteerAng_Val
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnSteerAng/ActRet
            Cdp_Prov_MaxMotTrqDepOnSteerAngA/MaxMotTrqDepOnSteerAngA/MaxMotTrqDepOnSteerAng */
         *MaxMotTrqDepOnSteerAng_Val = Tab1DIntp2I1T65_ARC((const uint16 *)
          &(Rte_CData_MaxMotTrqDepOnSteerAngA()[0]),
          y_index_mActRet_MaxMotorTorqueDepOnSteeringAngleA_XAU16_AxisX_ldU8,
          x_fraction_mActRet_MaxMotorTorqueDepOnSteeringAngleA_XAU16_AxisX_ldU16);
         break;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetCdp_ProvideMaxMotorTorqueDepOnVehSpeed
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCdp_CODE) ActRetCdp_ProvideMaxMotorTorqueDepOnVehSpeed(P2VAR(uint16,
  AUTOMATIC, RTE_APPL_DATA) MaxMotTrqDepOnVehSpd_Val, IDT_AbsMaxSafeVehSpd AbsMaxSafeVehSpd)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   IDT_ActChar ActChar; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 2 */

   /* TargetLink inport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActChar */
   Rte_Read_RP_ActChar_ActChar(&ActChar);

   /* SwitchCase: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/Switch Case */
   switch (ActChar) {
      case 1: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_mActRet_MaxMotorTorqueDepOnVehSpeedB_XAU16_AxisX_ldU16; /* LSB: 2^-16 OFF
         : 0 MIN/MAX: 0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_mActRet_MaxMotorTorqueDepOnVehSpeedB_XAU16_AxisX_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCdp_Prov_MaxMotTr
            qDepOnVehSpdB/MaxMotTrqDepOnVehSpdB/MaxMotTrqDepOnVehSpd_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMot
            TrqDepOnVehSpd/AbsMaxSafeVehSpd */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_MaxMotTrqDepOnVehSpdB_AxisX()[0]), 5,
          AbsMaxSafeVehSpd, &y_index_mActRet_MaxMotorTorqueDepOnVehSpeedB_XAU16_AxisX_ldU8,
          &x_fraction_mActRet_MaxMotorTorqueDepOnVehSpeedB_XAU16_AxisX_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSp
            d/ActRetCdp_Prov_MaxMotTrqDepOnVehSpdB/MaxMotTrqDepOnVehSpdB/MaxMotTrqDepOnVehSpd
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/Max
            MotTrqDepOnVehSpd_Val
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCd
            p_Prov_MaxMotTrqDepOnVehSpdB/MaxMotTrqDepOnVehSpdB/MaxMotTrqDepOnVehSpd */
         *MaxMotTrqDepOnVehSpd_Val = Tab1DIntp2I1T65_ARC((const uint16 *)
          &(Rte_CData_MaxMotTrqDepOnVehSpdB()[0]),
          y_index_mActRet_MaxMotorTorqueDepOnVehSpeedB_XAU16_AxisX_ldU8,
          x_fraction_mActRet_MaxMotorTorqueDepOnVehSpeedB_XAU16_AxisX_ldU16);
         break;
      }
      case 2: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_mActRet_MaxMotorTorqueDepOnVehSpeedC_XAU16_AxisX_ldU16; /* LSB: 2^-16 OFF
         : 0 MIN/MAX: 0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_mActRet_MaxMotorTorqueDepOnVehSpeedC_XAU16_AxisX_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCdp_Prov_MaxMotTr
            qDepOnVehSpdC/MaxMotTrqDepOnVehSpdC/MaxMotTrqDepOnVehSpd_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMot
            TrqDepOnVehSpd/AbsMaxSafeVehSpd */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_MaxMotTrqDepOnVehSpdC_AxisX()[0]), 5,
          AbsMaxSafeVehSpd, &y_index_mActRet_MaxMotorTorqueDepOnVehSpeedC_XAU16_AxisX_ldU8,
          &x_fraction_mActRet_MaxMotorTorqueDepOnVehSpeedC_XAU16_AxisX_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSp
            d/ActRetCdp_Prov_MaxMotTrqDepOnVehSpdC/MaxMotTrqDepOnVehSpdC/MaxMotTrqDepOnVehSpd
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/Max
            MotTrqDepOnVehSpd_Val
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCd
            p_Prov_MaxMotTrqDepOnVehSpdC/MaxMotTrqDepOnVehSpdC/MaxMotTrqDepOnVehSpd */
         *MaxMotTrqDepOnVehSpd_Val = Tab1DIntp2I1T65_ARC((const uint16 *)
          &(Rte_CData_MaxMotTrqDepOnVehSpdC()[0]),
          y_index_mActRet_MaxMotorTorqueDepOnVehSpeedC_XAU16_AxisX_ldU8,
          x_fraction_mActRet_MaxMotorTorqueDepOnVehSpeedC_XAU16_AxisX_ldU16);
         break;
      }
      default: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_mActRet_MaxMotorTorqueDepOnVehSpeedA_XAU16_AxisX_ldU16; /* LSB: 2^-16 OFF
         : 0 MIN/MAX: 0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_mActRet_MaxMotorTorqueDepOnVehSpeedA_XAU16_AxisX_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCdp_Prov_MaxMotTr
            qDepOnVehSpdA/MaxMotTrqDepOnVehSpdA/MaxMotTrqDepOnVehSpd_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMot
            TrqDepOnVehSpd/AbsMaxSafeVehSpd */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_MaxMotTrqDepOnVehSpdA_AxisX()[0]), 5,
          AbsMaxSafeVehSpd, &y_index_mActRet_MaxMotorTorqueDepOnVehSpeedA_XAU16_AxisX_ldU8,
          &x_fraction_mActRet_MaxMotorTorqueDepOnVehSpeedA_XAU16_AxisX_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSp
            d/ActRetCdp_Prov_MaxMotTrqDepOnVehSpdA/MaxMotTrqDepOnVehSpdA/MaxMotTrqDepOnVehSpd
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/Max
            MotTrqDepOnVehSpd_Val
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqDepOnVehSpd/ActRetCd
            p_Prov_MaxMotTrqDepOnVehSpdA/MaxMotTrqDepOnVehSpdA/MaxMotTrqDepOnVehSpd */
         *MaxMotTrqDepOnVehSpd_Val = Tab1DIntp2I1T65_ARC((const uint16 *)
          &(Rte_CData_MaxMotTrqDepOnVehSpdA()[0]),
          y_index_mActRet_MaxMotorTorqueDepOnVehSpeedA_XAU16_AxisX_ldU8,
          x_fraction_mActRet_MaxMotorTorqueDepOnVehSpeedA_XAU16_AxisX_ldU16);
         break;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetCdp_ProvideMaxTBT4ShutDown
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCdp_CODE) ActRetCdp_ProvideMaxTBT4ShutDown(P2VAR(uint8, AUTOMATIC,
  RTE_APPL_DATA) MaxTBT4ShtDwn_Val)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   IDT_ActChar ActChar; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 2 */

   /* TargetLink inport: ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/ActChar */
   Rte_Read_RP_ActChar_ActChar(&ActChar);

   /* SwitchCase: ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/Switch Case */
   switch (ActChar) {
      case 1: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/ActRe
            tCdp_Prov_MaxTBT4ShtDwnB/MaxTBT4ShtDwnB
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/MaxTBT4Sht
            Dwn_Val */
         *MaxTBT4ShtDwn_Val = Rte_CData_MaxTBT4ShtDwnB();
         break;
      }
      case 2: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/ActRe
            tCdp_Prov_MaxTBT4ShtDwnC/MaxTBT4ShtDwnC
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/MaxTBT4Sht
            Dwn_Val */
         *MaxTBT4ShtDwn_Val = Rte_CData_MaxTBT4ShtDwnC();
         break;
      }
      default: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/ActRe
            tCdp_Prov_MaxTBT4ShtDwnA/MaxTBT4ShtDwnA
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MaxTBT4ShtDwn/MaxTBT4Sht
            Dwn_Val */
         *MaxTBT4ShtDwn_Val = Rte_CData_MaxTBT4ShtDwnA();
         break;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetCdp_ProvideMotorTorqueGain
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCdp_CODE) ActRetCdp_ProvideMotorTorqueGain(P2VAR(uint16, AUTOMATIC,
  RTE_APPL_DATA) MotTrqGain_Val, IDT_AbsAvgVehSpd AbsAvgVehSpd)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   IDT_ActChar ActChar; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 2 */

   /* TargetLink inport: ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActChar */
   Rte_Read_RP_ActChar_ActChar(&ActChar);

   /* SwitchCase: ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/Switch Case */
   switch (ActChar) {
      case 1: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_xActRet_MotorTorqueGainB_XAU16_AxisX_ldU16; /* LSB: 2^-16 OFF: 0 MIN/MAX:
          0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_xActRet_MotorTorqueGainB_XAU16_AxisX_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_MotTrqGainB/MotTrq
            GainB/MotTrqGainB_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MotTrq
            Gain/AbsAvgVehSpd */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_MotTrqGainB_AxisX()[0]), 6, AbsAvgVehSpd,
          &y_index_xActRet_MotorTorqueGainB_XAU16_AxisX_ldU8,
          &x_fraction_xActRet_MotorTorqueGainB_XAU16_AxisX_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCd
            p_Prov_MotTrqGainB/MotTrqGainB/MotorTorqueGain
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/MotTrqGain_Va
            l
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_Mot
            TrqGainB/MotTrqGainB/MotorTorqueGain */
         *MotTrqGain_Val = Tab1DIntp2I1T65_ARC((const uint16 *) &(Rte_CData_MotTrqGainB()[0]),
          y_index_xActRet_MotorTorqueGainB_XAU16_AxisX_ldU8,
          x_fraction_xActRet_MotorTorqueGainB_XAU16_AxisX_ldU16);
         break;
      }
      case 2: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_xActRet_MotorTorqueGainC_XAU16_AxisX_ldU16; /* LSB: 2^-16 OFF: 0 MIN/MAX:
          0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_xActRet_MotorTorqueGainC_XAU16_AxisX_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_MotTrqGainC/MotTrq
            GainC/MotTrqGainC_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MotTrq
            Gain/AbsAvgVehSpd */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_MotTrqGainC_AxisX()[0]), 6, AbsAvgVehSpd,
          &y_index_xActRet_MotorTorqueGainC_XAU16_AxisX_ldU8,
          &x_fraction_xActRet_MotorTorqueGainC_XAU16_AxisX_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCd
            p_Prov_MotTrqGainC/MotTrqGainC/MotorTorqueGain
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/MotTrqGain_Va
            l
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_Mot
            TrqGainC/MotTrqGainC/MotorTorqueGain */
         *MotTrqGain_Val = Tab1DIntp2I1T65_ARC((const uint16 *) &(Rte_CData_MotTrqGainC()[0]),
          y_index_xActRet_MotorTorqueGainC_XAU16_AxisX_ldU8,
          x_fraction_xActRet_MotorTorqueGainC_XAU16_AxisX_ldU16);
         break;
      }
      default: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_xActRet_MotorTorqueGainA_XAU16_AxisX_ldU16; /* LSB: 2^-16 OFF: 0 MIN/MAX:
          0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_xActRet_MotorTorqueGaiAn_XAU16_AxisX_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_MotTrqGainA/MotTrq
            GainA/MotTrqGainA_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MotTrq
            Gain/AbsAvgVehSpd */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_MotTrqGainA_AxisX()[0]), 6, AbsAvgVehSpd,
          &y_index_xActRet_MotorTorqueGaiAn_XAU16_AxisX_ldU8,
          &x_fraction_xActRet_MotorTorqueGainA_XAU16_AxisX_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCd
            p_Prov_MotTrqGainA/MotTrqGainA/MotorTorqueGain
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/MotTrqGain_Va
            l
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_MotTrqGain/ActRetCdp_Prov_Mot
            TrqGainA/MotTrqGainA/MotorTorqueGain */
         *MotTrqGain_Val = Tab1DIntp2I1T65_ARC((const uint16 *) &(Rte_CData_MotTrqGainA()[0]),
          y_index_xActRet_MotorTorqueGaiAn_XAU16_AxisX_ldU8,
          x_fraction_xActRet_MotorTorqueGainA_XAU16_AxisX_ldU16);
         break;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetCdp_ProvideNominalSteeringSpeed
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCdp_CODE) ActRetCdp_ProvideNominalSteeringSpeed(P2VAR(uint16, AUTOMATIC,
  RTE_APPL_DATA) NomSteerSpd_Val, IDT_AbsAvgVehSpd AbsAvgVehSpd, IDT_AbsSteerAng AbsSteerAng)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   IDT_ActChar ActChar; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 2 */

   /* TargetLink inport: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActChar */
   Rte_Read_RP_ActChar_ActChar(&ActChar);

   /* SwitchCase: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/Switch Case */
   switch (ActChar) {
      case 1: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_vActRet_NominalSteeringSpeedB_XAU16_AxisX_ldU16; /* LSB: 2^-16 OFF: 0 MIN
         /MAX: 0 .. 0.999984741210938 */
         uint16 x_fraction_vActRet_NominalSteeringSpeedB_XAU16_AxisY_ldU16; /* LSB: 2^-16 OFF: 0 MIN
         /MAX: 0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_vActRet_NominalSteeringSpeedB_XAU16_AxisX_ldU8;
         uint8 y_index_vActRet_NominalSteeringSpeedB_XAU16_AxisY_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdB/NomS
            teerSpdB/NomSteerSpdB_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_NomSte
            erSpd/AbsAvgVehSpd */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_NomSteerSpdB_AxisX()[0]), 6, AbsAvgVehSpd,
          &y_index_vActRet_NominalSteeringSpeedB_XAU16_AxisX_ldU8,
          &x_fraction_vActRet_NominalSteeringSpeedB_XAU16_AxisX_ldU16);

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdB/NomS
            teerSpdB/NomSteerSpdB_AxisY_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_NomSte
            erSpd/AbsSteerAng */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_NomSteerSpdB_AxisY()[0]), 13, AbsSteerAng,
          &y_index_vActRet_NominalSteeringSpeedB_XAU16_AxisY_ldU8,
          &x_fraction_vActRet_NominalSteeringSpeedB_XAU16_AxisY_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetC
            dp_Prov_NomSteerSpdB/NomSteerSpdB/NominalSteeringSpeedB
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/NomSteerSpd_
            Val
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_No
            mSteerSpdB/NomSteerSpdB/NominalSteeringSpeedB */
         *NomSteerSpd_Val = Tab2DIntp2I1T33281_ARC((const uint16 *) Rte_CData_NomSteerSpdB(), 13,
          y_index_vActRet_NominalSteeringSpeedB_XAU16_AxisX_ldU8,
          x_fraction_vActRet_NominalSteeringSpeedB_XAU16_AxisX_ldU16,
          y_index_vActRet_NominalSteeringSpeedB_XAU16_AxisY_ldU8,
          x_fraction_vActRet_NominalSteeringSpeedB_XAU16_AxisY_ldU16);
         break;
      }
      case 2: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_vActRet_NominalSteeringSpeedC_XAU16_AxisX_ldU16; /* LSB: 2^-16 OFF: 0 MIN
         /MAX: 0 .. 0.999984741210938 */
         uint16 x_fraction_vActRet_NominalSteeringSpeedC_XAU16_AxisY_ldU16; /* LSB: 2^-16 OFF: 0 MIN
         /MAX: 0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_vActRet_NominalSteeringSpeedC_XAU16_AxisX_ldU8;
         uint8 y_index_vActRet_NominalSteeringSpeedC_XAU16_AxisY_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdC/NomS
            teerSpdC/NomSteerSpdC_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_NomSte
            erSpd/AbsAvgVehSpd */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_NomSteerSpdC_AxisX()[0]), 6, AbsAvgVehSpd,
          &y_index_vActRet_NominalSteeringSpeedC_XAU16_AxisX_ldU8,
          &x_fraction_vActRet_NominalSteeringSpeedC_XAU16_AxisX_ldU16);

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdC/NomS
            teerSpdC/NomSteerSpdC_AxisY_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_NomSte
            erSpd/AbsSteerAng */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_NomSteerSpdC_AxisY()[0]), 13, AbsSteerAng,
          &y_index_vActRet_NominalSteeringSpeedC_XAU16_AxisY_ldU8,
          &x_fraction_vActRet_NominalSteeringSpeedC_XAU16_AxisY_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetC
            dp_Prov_NomSteerSpdC/NomSteerSpdC/NominalSteeringSpeedC
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/NomSteerSpd_
            Val
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_No
            mSteerSpdC/NomSteerSpdC/NominalSteeringSpeedC */
         *NomSteerSpd_Val = Tab2DIntp2I1T33281_ARC((const uint16 *) Rte_CData_NomSteerSpdC(), 13,
          y_index_vActRet_NominalSteeringSpeedC_XAU16_AxisX_ldU8,
          x_fraction_vActRet_NominalSteeringSpeedC_XAU16_AxisX_ldU16,
          y_index_vActRet_NominalSteeringSpeedC_XAU16_AxisY_ldU8,
          x_fraction_vActRet_NominalSteeringSpeedC_XAU16_AxisY_ldU16);
         break;
      }
      default: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_vActRet_NominalSteeringSpeedA_XAU16_AxisX_ldU16; /* LSB: 2^-16 OFF: 0 MIN
         /MAX: 0 .. 0.999984741210938 */
         uint16 x_fraction_vActRet_NominalSteeringSpeedA_XAU16_AxisY_ldU16; /* LSB: 2^-16 OFF: 0 MIN
         /MAX: 0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_vActRet_NominalSteeringSpeedA_XAU16_AxisX_ldU8;
         uint8 y_index_vActRet_NominalSteeringSpeedA_XAU16_AxisY_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdA/NomS
            teerSpdA/NomSteerSpdA_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_NomSte
            erSpd/AbsAvgVehSpd */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_NomSteerSpdA_AxisX()[0]), 6, AbsAvgVehSpd,
          &y_index_vActRet_NominalSteeringSpeedA_XAU16_AxisX_ldU8,
          &x_fraction_vActRet_NominalSteeringSpeedA_XAU16_AxisX_ldU16);

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_NomSteerSpdA/NomS
            teerSpdA/NomSteerSpdA_AxisY_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_NomSte
            erSpd/AbsSteerAng */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_NomSteerSpdA_AxisY()[0]), 13, AbsSteerAng,
          &y_index_vActRet_NominalSteeringSpeedA_XAU16_AxisY_ldU8,
          &x_fraction_vActRet_NominalSteeringSpeedA_XAU16_AxisY_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetC
            dp_Prov_NomSteerSpdA/NomSteerSpdA/NominalSteeringSpeedA
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/NomSteerSpd_
            Val
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_NomSteerSpd/ActRetCdp_Prov_No
            mSteerSpdA/NomSteerSpdA/NominalSteeringSpeedA */
         *NomSteerSpd_Val = Tab2DIntp2I1T33281_ARC((const uint16 *) Rte_CData_NomSteerSpdA(), 13,
          y_index_vActRet_NominalSteeringSpeedA_XAU16_AxisX_ldU8,
          x_fraction_vActRet_NominalSteeringSpeedA_XAU16_AxisX_ldU16,
          y_index_vActRet_NominalSteeringSpeedA_XAU16_AxisY_ldU8,
          x_fraction_vActRet_NominalSteeringSpeedA_XAU16_AxisY_ldU16);
         break;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetCdp_ProvideRetTorqueFactDepOnDriver
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCdp_CODE) ActRetCdp_ProvideRetTorqueFactDepOnDriver(P2VAR(uint16, AUTOMATIC,
  RTE_APPL_DATA) RetTrqFactDepOnDrvr_Val, IDT_AbsDrvrTrq AbsDrvrTrq, IDT_AbsAvgVehSpd AbsAvgVehSpd)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   IDT_ActChar ActChar; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 2 */

   /* TargetLink inport: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActChar */
   Rte_Read_RP_ActChar_ActChar(&ActChar);

   /* SwitchCase: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/Switch Case */
   switch (ActChar) {
      case 1: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_xActRet_RetTorqueFactDepOnDriverB_XAU16_AxisX_ldU16; /* LSB: 2^-16 OFF: 0
          MIN/MAX: 0 .. 0.999984741210938 */
         uint16 x_fraction_xActRet_RetTorqueFactDepOnDriverB_XAU16_AxisY_ldU16; /* LSB: 2^-16 OFF: 0
          MIN/MAX: 0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_xActRet_RetTorqueFactDepOnDriverB_XAU16_AxisX_ldU8;
         uint8 y_index_xActRet_RetTorqueFactDepOnDriverB_XAU16_AxisY_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFac
            tDepOnDrvrB/RetTrqFactDepOnDrvrB/RetTrqFactDepOnDrvrB_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_RetTrq
            FactDepOnDrvr/AbsDrvrTrq */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_RetTrqFactDepOnDrvrB_AxisX()[0]), 6,
          AbsDrvrTrq, &y_index_xActRet_RetTorqueFactDepOnDriverB_XAU16_AxisX_ldU8,
          &x_fraction_xActRet_RetTorqueFactDepOnDriverB_XAU16_AxisX_ldU16);

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFac
            tDepOnDrvrB/RetTrqFactDepOnDrvrB/RetTrqFactDepOnDrvrB_AxisY_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_RetTrq
            FactDepOnDrvr/AbsAvgVehSpd */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_RetTrqFactDepOnDrvrB_AxisY()[0]), 3,
          AbsAvgVehSpd, &y_index_xActRet_RetTorqueFactDepOnDriverB_XAU16_AxisY_ldU8,
          &x_fraction_xActRet_RetTorqueFactDepOnDriverB_XAU16_AxisY_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr
            /ActRetCdp_Prov_RetTrqFactDepOnDrvrB/RetTrqFactDepOnDrvrB/RetTrqFactDepOnDrvr
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/RetT
            rqFactDepOnDrvr_Val
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp
            _Prov_RetTrqFactDepOnDrvrB/RetTrqFactDepOnDrvrB/RetTrqFactDepOnDrvr */
         *RetTrqFactDepOnDrvr_Val = Tab2DIntp2I1T33281_ARC((const uint16 *)
          Rte_CData_RetTrqFactDepOnDrvrB(), 3,
          y_index_xActRet_RetTorqueFactDepOnDriverB_XAU16_AxisX_ldU8,
          x_fraction_xActRet_RetTorqueFactDepOnDriverB_XAU16_AxisX_ldU16,
          y_index_xActRet_RetTorqueFactDepOnDriverB_XAU16_AxisY_ldU8,
          x_fraction_xActRet_RetTorqueFactDepOnDriverB_XAU16_AxisY_ldU16);
         break;
      }
      case 2: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_xActRet_RetTorqueFactDepOnDriverC_XAU16_AxisX_ldU16; /* LSB: 2^-16 OFF: 0
          MIN/MAX: 0 .. 0.999984741210938 */
         uint16 x_fraction_xActRet_RetTorqueFactDepOnDriverC_XAU16_AxisY_ldU16; /* LSB: 2^-16 OFF: 0
          MIN/MAX: 0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_xActRet_RetTorqueFactDepOnDriverC_XAU16_AxisX_ldU8;
         uint8 y_index_xActRet_RetTorqueFactDepOnDriverC_XAU16_AxisY_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFac
            tDepOnDrvrC/RetTrqFactDepOnDrvrC/RetTrqFactDepOnDrvrC_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_RetTrq
            FactDepOnDrvr/AbsDrvrTrq */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_RetTrqFactDepOnDrvrC_AxisX()[0]), 6,
          AbsDrvrTrq, &y_index_xActRet_RetTorqueFactDepOnDriverC_XAU16_AxisX_ldU8,
          &x_fraction_xActRet_RetTorqueFactDepOnDriverC_XAU16_AxisX_ldU16);

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFac
            tDepOnDrvrC/RetTrqFactDepOnDrvrC/RetTrqFactDepOnDrvrC_AxisY_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_RetTrq
            FactDepOnDrvr/AbsAvgVehSpd */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_RetTrqFactDepOnDrvrC_AxisY()[0]), 3,
          AbsAvgVehSpd, &y_index_xActRet_RetTorqueFactDepOnDriverC_XAU16_AxisY_ldU8,
          &x_fraction_xActRet_RetTorqueFactDepOnDriverC_XAU16_AxisY_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr
            /ActRetCdp_Prov_RetTrqFactDepOnDrvrC/RetTrqFactDepOnDrvrC/RetTrqFactDepOnDrvr
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/RetT
            rqFactDepOnDrvr_Val
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp
            _Prov_RetTrqFactDepOnDrvrC/RetTrqFactDepOnDrvrC/RetTrqFactDepOnDrvr */
         *RetTrqFactDepOnDrvr_Val = Tab2DIntp2I1T33281_ARC((const uint16 *)
          Rte_CData_RetTrqFactDepOnDrvrC(), 3,
          y_index_xActRet_RetTorqueFactDepOnDriverC_XAU16_AxisX_ldU8,
          x_fraction_xActRet_RetTorqueFactDepOnDriverC_XAU16_AxisX_ldU16,
          y_index_xActRet_RetTorqueFactDepOnDriverC_XAU16_AxisY_ldU8,
          x_fraction_xActRet_RetTorqueFactDepOnDriverC_XAU16_AxisY_ldU16);
         break;
      }
      default: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_xActRet_RetTorqueFactDepOnDriverA_XAU16_AxisX_ldU16; /* LSB: 2^-16 OFF: 0
          MIN/MAX: 0 .. 0.999984741210938 */
         uint16 x_fraction_xActRet_RetTorqueFactDepOnDriverA_XAU16_AxisY_ldU16; /* LSB: 2^-16 OFF: 0
          MIN/MAX: 0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_xActRet_RetTorqueFactDepOnDriverA_XAU16_AxisX_ldU8;
         uint8 y_index_xActRet_RetTorqueFactDepOnDriverA_XAU16_AxisY_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFac
            tDepOnDrvrA/RetTrqFactDepOnDrvrA/RetTrqFactDepOnDrvrA_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_RetTrq
            FactDepOnDrvr/AbsDrvrTrq */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_RetTrqFactDepOnDrvrA_AxisX()[0]), 6,
          AbsDrvrTrq, &y_index_xActRet_RetTorqueFactDepOnDriverA_XAU16_AxisX_ldU8,
          &x_fraction_xActRet_RetTorqueFactDepOnDriverA_XAU16_AxisX_ldU16);

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp_Prov_RetTrqFac
            tDepOnDrvrA/RetTrqFactDepOnDrvrA/RetTrqFactDepOnDrvrA_AxisY_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_RetTrq
            FactDepOnDrvr/AbsAvgVehSpd */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_RetTrqFactDepOnDrvrA_AxisY()[0]), 3,
          AbsAvgVehSpd, &y_index_xActRet_RetTorqueFactDepOnDriverA_XAU16_AxisY_ldU8,
          &x_fraction_xActRet_RetTorqueFactDepOnDriverA_XAU16_AxisY_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr
            /ActRetCdp_Prov_RetTrqFactDepOnDrvrA/RetTrqFactDepOnDrvrA/RetTrqFactDepOnDriver
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/RetT
            rqFactDepOnDrvr_Val
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_RetTrqFactDepOnDrvr/ActRetCdp
            _Prov_RetTrqFactDepOnDrvrA/RetTrqFactDepOnDrvrA/RetTrqFactDepOnDriver */
         *RetTrqFactDepOnDrvr_Val = Tab2DIntp2I1T33281_ARC((const uint16 *)
          Rte_CData_RetTrqFactDepOnDrvrA(), 3,
          y_index_xActRet_RetTorqueFactDepOnDriverA_XAU16_AxisX_ldU8,
          x_fraction_xActRet_RetTorqueFactDepOnDriverA_XAU16_AxisX_ldU16,
          y_index_xActRet_RetTorqueFactDepOnDriverA_XAU16_AxisY_ldU8,
          x_fraction_xActRet_RetTorqueFactDepOnDriverA_XAU16_AxisY_ldU16);
         break;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetCdp_ProvideSteerSpeedFactDepOnDriver
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCdp_CODE) ActRetCdp_ProvideSteerSpeedFactDepOnDriver(P2VAR(uint16, AUTOMATIC,
  RTE_APPL_DATA) SteerSpdFactDepOnDrvr_Val, IDT_AbsDrvrTrq AbsDrvrTrq, IDT_AbsAvgVehSpd
  AbsAvgVehSpd)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   IDT_ActChar ActChar; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 2 */

   /* TargetLink inport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActChar */
   Rte_Read_RP_ActChar_ActChar(&ActChar);

   /* SwitchCase: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/Switch Case */
   switch (ActChar) {
      case 1: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_xActRet_SteerSpeedFactDepOnDriverB_XAU16_AxisX_ldU16; /* LSB: 2^-16 OFF: 
         0 MIN/MAX: 0 .. 0.999984741210938 */
         uint16 x_fraction_xActRet_SteerSpeedFactDepOnDriverB_XAU16_XAU16_AxisY_ldU16; /* LSB: 2^-16
          OFF: 0 MIN/MAX: 0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_xActRet_SteerSpeedFactDepOnDriverB_XAU16_AxisX_ldU8;
         uint8 y_index_xActRet_SteerSpeedFactDepOnDriverB_XAU16_AxisY_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSp
            dFactDepOnDrvrB/SteerSpdFactDepOnDrvrB/SteerSpdFactDepOnDrvrB_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerS
            pdFactDepOnDrvr/AbsDrvrTrq */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_SteerSpdFactDepOnDrvrB_AxisX()[0]), 6,
          AbsDrvrTrq, &y_index_xActRet_SteerSpeedFactDepOnDriverB_XAU16_AxisX_ldU8,
          &x_fraction_xActRet_SteerSpeedFactDepOnDriverB_XAU16_AxisX_ldU16);

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSp
            dFactDepOnDrvrB/SteerSpdFactDepOnDrvrB/SteerSpdFactDepOnDrvrB_AxisY_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerS
            pdFactDepOnDrvr/AbsAvgVehSpd */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_SteerSpdFactDepOnDrvrB_AxisY()[0]), 3,
          AbsAvgVehSpd, &y_index_xActRet_SteerSpeedFactDepOnDriverB_XAU16_AxisY_ldU8,
          &x_fraction_xActRet_SteerSpeedFactDepOnDriverB_XAU16_XAU16_AxisY_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDr
            vr/ActRetCdp_Prov_SteerSpdFactDepOnDrvrB/SteerSpdFactDepOnDrvrB/SteerSpdFactDepOnDrvr
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/St
            eerSpdFactDepOnDrvr_Val
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetC
            dp_Prov_SteerSpdFactDepOnDrvrB/SteerSpdFactDepOnDrvrB/SteerSpdFactDepOnDrvr */
         *SteerSpdFactDepOnDrvr_Val = Tab2DIntp2I1T33281_ARC((const uint16 *)
          Rte_CData_SteerSpdFactDepOnDrvrB(), 3,
          y_index_xActRet_SteerSpeedFactDepOnDriverB_XAU16_AxisX_ldU8,
          x_fraction_xActRet_SteerSpeedFactDepOnDriverB_XAU16_AxisX_ldU16,
          y_index_xActRet_SteerSpeedFactDepOnDriverB_XAU16_AxisY_ldU8,
          x_fraction_xActRet_SteerSpeedFactDepOnDriverB_XAU16_XAU16_AxisY_ldU16);
         break;
      }
      case 2: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_xActRet_SteerSpeedFactDepOnDriverC_XAU16_AxisX_ldU16; /* LSB: 2^-16 OFF: 
         0 MIN/MAX: 0 .. 0.999984741210938 */
         uint16 x_fraction_xActRet_SteerSpeedFactDepOnDriverC_XAU16_AxisY_ldU16; /* LSB: 2^-16 OFF: 
         0 MIN/MAX: 0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_xActRet_SteerSpeedFactDepOnDriverC_XAU16_AxisX_ldU8;
         uint8 y_index_xActRet_SteerSpeedFactDepOnDriverC_XAU16_AxisY_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSp
            dFactDepOnDrvrC/SteerSpdFactDepOnDrvrC/SteerSpdFactDepOnDrvrC_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerS
            pdFactDepOnDrvr/AbsDrvrTrq */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_SteerSpdFactDepOnDrvrC_AxisX()[0]), 6,
          AbsDrvrTrq, &y_index_xActRet_SteerSpeedFactDepOnDriverC_XAU16_AxisX_ldU8,
          &x_fraction_xActRet_SteerSpeedFactDepOnDriverC_XAU16_AxisX_ldU16);

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSp
            dFactDepOnDrvrC/SteerSpdFactDepOnDrvrC/SteerSpdFactDepOnDrvrC_AxisY_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerS
            pdFactDepOnDrvr/AbsAvgVehSpd */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_SteerSpdFactDepOnDrvrC_AxisY()[0]), 3,
          AbsAvgVehSpd, &y_index_xActRet_SteerSpeedFactDepOnDriverC_XAU16_AxisY_ldU8,
          &x_fraction_xActRet_SteerSpeedFactDepOnDriverC_XAU16_AxisY_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDr
            vr/ActRetCdp_Prov_SteerSpdFactDepOnDrvrC/SteerSpdFactDepOnDrvrC/SteerSpdFactDepOnDrvr
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/St
            eerSpdFactDepOnDrvr_Val
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetC
            dp_Prov_SteerSpdFactDepOnDrvrC/SteerSpdFactDepOnDrvrC/SteerSpdFactDepOnDrvr */
         *SteerSpdFactDepOnDrvr_Val = Tab2DIntp2I1T33281_ARC((const uint16 *)
          Rte_CData_SteerSpdFactDepOnDrvrC(), 3,
          y_index_xActRet_SteerSpeedFactDepOnDriverC_XAU16_AxisX_ldU8,
          x_fraction_xActRet_SteerSpeedFactDepOnDriverC_XAU16_AxisX_ldU16,
          y_index_xActRet_SteerSpeedFactDepOnDriverC_XAU16_AxisY_ldU8,
          x_fraction_xActRet_SteerSpeedFactDepOnDriverC_XAU16_AxisY_ldU16);
         break;
      }
      default: {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         uint16 x_fraction_xActRet_SteerSpeedFactDepOnDriverA_XAU16_AxisX_ldU16; /* LSB: 2^-16 OFF: 
         0 MIN/MAX: 0 .. 0.999984741210938 */
         uint16 x_fraction_xActRet_SteerSpeedFactDepOnDriverA_XAU16_AxisY_ldU16; /* LSB: 2^-16 OFF: 
         0 MIN/MAX: 0 .. 0.999984741210938 */

         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 y_index_xActRet_SteerSpeedFactDepOnDriverA_XAU16_AxisX_ldU8;
         uint8 y_index_xActRet_SteerSpeedFactDepOnDriverA_XAU16_AxisY_ldU8;

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSp
            dFactDepOnDrvrA/xActRet_SteerSpeedFactDepOnDriverA/SteerSpdFactDepOnDrvrA_AxisX_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerS
            pdFactDepOnDrvr/AbsDrvrTrq */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_SteerSpdFactDepOnDrvrA_AxisX()[0]), 6,
          AbsDrvrTrq, &y_index_xActRet_SteerSpeedFactDepOnDriverA_XAU16_AxisX_ldU8,
          &x_fraction_xActRet_SteerSpeedFactDepOnDriverA_XAU16_AxisX_ldU16);

         /* IndexSearch: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetCdp_Prov_SteerSp
            dFactDepOnDrvrA/xActRet_SteerSpeedFactDepOnDriverA/SteerSpdFactDepOnDrvrA_AxisY_unique
            # combined # update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerS
            pdFactDepOnDrvr/AbsAvgVehSpd */
         TabIdxS48T513_ARC((const uint16 *) &(Rte_CData_SteerSpdFactDepOnDrvrA_AxisY()[0]), 3,
          AbsAvgVehSpd, &y_index_xActRet_SteerSpeedFactDepOnDriverA_XAU16_AxisY_ldU8,
          &x_fraction_xActRet_SteerSpeedFactDepOnDriverA_XAU16_AxisY_ldU16);

         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDr
            vr/ActRetCdp_Prov_SteerSpdFactDepOnDrvrA/xActRet_SteerSpeedFactDepOnDriverA/SteerSpdFact
            DepOnDrvr
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/St
            eerSpdFactDepOnDrvr_Val
            # combined # Interpolation: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFactDepOnDrvr/ActRetC
            dp_Prov_SteerSpdFactDepOnDrvrA/xActRet_SteerSpeedFactDepOnDriverA/SteerSpdFactDepOnDrvr
             */
         *SteerSpdFactDepOnDrvr_Val = Tab2DIntp2I1T33281_ARC((const uint16 *)
          Rte_CData_SteerSpdFactDepOnDrvrA(), 3,
          y_index_xActRet_SteerSpeedFactDepOnDriverA_XAU16_AxisX_ldU8,
          x_fraction_xActRet_SteerSpeedFactDepOnDriverA_XAU16_AxisX_ldU16,
          y_index_xActRet_SteerSpeedFactDepOnDriverA_XAU16_AxisY_ldU8,
          x_fraction_xActRet_SteerSpeedFactDepOnDriverA_XAU16_AxisY_ldU16);
         break;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetCdp_ProvideSteerSpeedGradAfterInvalid
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCdp_CODE) ActRetCdp_ProvideSteerSpeedGradAfterInvalid(P2VAR(uint16,
  AUTOMATIC, RTE_APPL_DATA) SteerSpdGradAftInvld_Val)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   IDT_ActChar ActChar; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 2 */

   /* TargetLink inport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld/ActChar */
   Rte_Read_RP_ActChar_ActChar(&ActChar);

   /* SwitchCase: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld/Switch Case */
   switch (ActChar) {
      case 1: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvl
            d/ActRetCdp_Prov_SteerSpdGradAftInvldB/SteerSpdGradAftInvldB
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld/Ste
            erSpdGradAftInvld_Val */
         *SteerSpdGradAftInvld_Val = Rte_CData_SteerSpdGradAftInvldB();
         break;
      }
      case 2: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvl
            d/ActRetCdp_Prov_SteerSpdGradAftInvldC/SteerSpdGradAftInvldC
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld/Ste
            erSpdGradAftInvld_Val */
         *SteerSpdGradAftInvld_Val = Rte_CData_SteerSpdGradAftInvldC();
         break;
      }
      default: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvl
            d/ActRetCdp_Prov_SteerSpdGradAftInvldA/SteerSpdGradAftInvldA
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdGradAftInvld/Ste
            erSpdGradAftInvld_Val */
         *SteerSpdGradAftInvld_Val = Rte_CData_SteerSpdGradAftInvldA();
         break;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetCdp_ProvideSteeringSpeedAmp
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCdp_CODE) ActRetCdp_ProvideSteeringSpeedAmp(P2VAR(uint16, AUTOMATIC,
  RTE_APPL_DATA) SteerSpdAmp_Val)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   IDT_ActChar ActChar; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 2 */

   /* TargetLink inport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/ActChar */
   Rte_Read_RP_ActChar_ActChar(&ActChar);

   /* SwitchCase: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/Switch Case */
   switch (ActChar) {
      case 1: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/ActRetC
            dp_Prov_SteerSpdAmpB/SteerSpdAmpB
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/SteerSpdAmp_
            Val */
         *SteerSpdAmp_Val = Rte_CData_SteerSpdAmpB();
         break;
      }
      case 2: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/ActRetC
            dp_Prov_SteerSpdAmpC/SteerSpdAmpC
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/SteerSpdAmp_
            Val */
         *SteerSpdAmp_Val = Rte_CData_SteerSpdAmpC();
         break;
      }
      default: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/ActRetC
            dp_Prov_SteerSpdAmpA/SteerSpdAmpA
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdAmp/SteerSpdAmp_
            Val */
         *SteerSpdAmp_Val = Rte_CData_SteerSpdAmpA();
         break;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActRetCdp_ProvideSteeringSpeedFact
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCdp_CODE) ActRetCdp_ProvideSteeringSpeedFact(P2VAR(uint8, AUTOMATIC,
  RTE_APPL_DATA) SteerSpdFact_Val)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   IDT_ActChar ActChar; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 2 */

   /* TargetLink inport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/ActChar */
   Rte_Read_RP_ActChar_ActChar(&ActChar);

   /* SwitchCase: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/Switch Case */
   switch (ActChar) {
      case 1: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/ActRet
            Cdp_Prov_SteerSpdFactB/SteerSpdFactB
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/SteerSpdFac
            t_Val */
         *SteerSpdFact_Val = Rte_CData_SteerSpdFactB();
         break;
      }
      case 2: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/ActRet
            Cdp_Prov_SteerSpdFactC/SteerSpdFactC
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/SteerSpdFac
            t_Val */
         *SteerSpdFact_Val = Rte_CData_SteerSpdFactC();
         break;
      }
      default: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/ActRet
            Cdp_Prov_SteerSpdFactA/SteerSpdFactA
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_SteerSpdFact/SteerSpdFac
            t_Val */
         *SteerSpdFact_Val = Rte_CData_SteerSpdFactA();
         break;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      ActiveReturnCdp_ActRetCdp_Prov_MaxMotTrqAftLoadFac
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
FUNC(void, ActiveReturnCdp_CODE)
  ActiveReturnCdp_ActRetCdp_Prov_MaxMotTrqAftLoadFac(P2VAR(IDT_MaxMotTrqAftLoadFac, AUTOMATIC,
  RTE_APPL_DATA) MaxMotTrqAftLoadFac_Val)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   IDT_ActChar ActChar; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 2 */

   /* TargetLink inport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac/ActChar */
   Rte_Read_RP_ActChar_ActChar(&ActChar);

   /* SwitchCase: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac/Switch Case */
   switch (ActChar) {
      case 1: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac
            /ActRetCdp_Prov_MaxMotTrqAftLoadFacB/MaxMotTrqAftLoadFacB
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac/MaxM
            otTrqAftLoadFac_Val */
         *MaxMotTrqAftLoadFac_Val = Rte_CData_MaxMotTrqAftLoadFacB();
         break;
      }
      case 2: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac
            /ActRetCdp_Prov_MaxMotTrqAftLoadFacC/MaxMotTrqAftLoadFacC
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac/MaxM
            otTrqAftLoadFac_Val */
         *MaxMotTrqAftLoadFac_Val = Rte_CData_MaxMotTrqAftLoadFacC();
         break;
      }
      default: {
         /* Merge: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac/Merge
            update of variable(s) associated with ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac
            /ActRetCdp_Prov_MaxMotTrqAftLoadFacA/MaxMotTrqAftLoadFacA
            # combined # TargetLink outport: ActiveReturnCdp/ActRetCdp_Prov_MaxMotTrqAftLoadFac/MaxM
            otTrqAftLoadFac_Val */
         *MaxMotTrqAftLoadFac_Val = Rte_CData_MaxMotTrqAftLoadFacA();
         break;
      }
   }
}

/* end of memory section 'CODE' */
#define ActiveReturnCdp_STOP_SEC_CODE
#include "ActiveReturnCdp_MemMap.h"

/*------------------------------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/
#endif /* IACTIVERETURNCDP_GG_C */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/

