% Main script for the generation of test cases of the 
% TargetLink lookup tables for ActiveReturnCdp
clear;
clc;

global sim_interp2_data;
sim_interp2_data = struct( ...
    'table_in_x', 0, ...
    'table_in_y', 0, ...
    'axis_x', [0, 1], ...
    'axis_y', [0, 1], ...
    'axis_z', [0 1; 1 2] ...
    );

dsdd('Open', './../../../design/ActiveReturnCdp_dd.dd');

st = mkdir('Data');

plot_settings.legend_settings = ...
    {'Interpreter', 'none', 'Location', 'NorthEastOutside'};
plot_settings.title_settings = ...
    {'Interpreter', 'none', 'FontSize', 8};
plot_settings.tc_name = ...
    'TC_Provide_Maximum_Motor_Torque_Dependent_on_Steering_Angle';

generate_test_data_1D( ...
    plot_settings.tc_name, ...
    'wApplI_AbsSteeringAngle_xdu16', ...
    'mActRet_MaxMotorTorqueDepOnSteeringAngle_XAU16', ...
    'sActRetI_SetSwitch_xdu8', ...
    1, 10, 4, 4, ...
    plot_settings ...
    );

plot_settings.tc_name = ...
    'TC_Provide_Maximum_Motor_Torque_Dependent_on_Vehicle_Speed';
generate_test_data_1D( ...
    plot_settings.tc_name, ...
    'vVehSpI_AbsMaxSafeVehSpd_xdu16', ...
    'mActRet_MaxMotorTorqueDepOnVehSpeed_XAU16', ...
    'sActRetI_SetSwitch_xdu8', ...
    2, 10, 4, 4, ...
    plot_settings ...
    );

plot_settings.tc_name = 'TC_Provide_Motor_Torque_Gain';
generate_test_data_1D( ...
    plot_settings.tc_name, ...
    'vVehSpI_AbsAvgVehSpd_xdu16', ...
    'xActRet_MotorTorqueGain_XAU16', ...
    'sActRetI_SetSwitch_xdu8', ...
    3, 10, 4, 4, ...
    plot_settings ...
    );

plot_settings.tc_name = ...
    'TC_Provide_Ret_Torque_Factor_Dependent_on_Driver';
generate_test_data_1D( ...
    plot_settings.tc_name, ...
    'mApplI_AbsDriverTorque_xdu16', ...
    'xActRet_RetTorqueFactDepOnDriver_XAU16', ...
    'sActRetI_SetSwitch_xdu8', ...
    4, 10, 4, 4, ...
    plot_settings ...
    );

plot_settings.tc_name = ...
    'TC_Provide_Steer_Speed_Factor_Dependent_on_Driver';
generate_test_data_1D( ...
    plot_settings.tc_name, ...
    'mApplI_AbsDriverTorque_xdu16', ...
    'xActRet_SteerSpeedFactDepOnDriver_XAU16', ...
    'sActRetI_SetSwitch_xdu8', ...
    5, 10, 4, 4, ...
    plot_settings ...
    );

plot_settings.tc_name = 'TC_Provide_Nominal_Steering_Speed';
generate_test_data_2D( ...
    plot_settings.tc_name, ...
    'vVehSpI_AbsAvgVehSpd_xdu16', ...
    'wApplI_AbsSteeringAngle_xdu16', ...
    'vActRet_NominalSteeringSpeed_XAU16', ...
    'sActRetI_SetSwitch_xdu8', ...
    6, 4, 4, 4, 4, ...
    plot_settings ...
    );