% Generation of the test cases for 1D lookup tables in TargetLink
function generate_test_data_1D( ...
    tc_name, ...
    table_in_name, ...
    table_out_name, ...
    switch_name, ...
    seed, ...
    n_io, ...
    rwf_cal, ...
    rwf_io, ...
    plot_settings ...
    )

    
%% background for calibration

rng(seed);

get_dd = @(str) strcat('get_', str, '_dd');
get_first_cell = @(x) x{1};

table_out_name_parts = split(table_out_name, '_');
table_AxisX_name = get_first_cell(join([table_out_name_parts; 'AxisX'], '_'));
table_out_Value_name = get_first_cell(join([table_out_name_parts; 'Value'], '_'));

table_out_A_name_parts = table_out_name_parts;
table_out_A_name_parts{2} = strcat(table_out_A_name_parts{2}, 'A');
table_out_A_name = get_first_cell(join(table_out_A_name_parts, '_'));
table_out_B_name_parts = table_out_name_parts;
table_out_B_name_parts{2} = strcat(table_out_B_name_parts{2}, 'B');
table_out_B_name = get_first_cell(join(table_out_B_name_parts, '_'));
table_out_C_name_parts = table_out_name_parts;
table_out_C_name_parts{2} = strcat(table_out_C_name_parts{2}, 'C');
table_out_C_name = get_first_cell(join(table_out_C_name_parts, '_'));


%% read dd

table_in_dd = TC_DD_Data.(get_dd(table_in_name));
table_axis_x_dd = TC_DD_Data.(get_dd(table_AxisX_name));
table_out_dd = TC_DD_Data.(get_dd(table_out_Value_name));


%% calculate test data

[cal, io] = get_TC_interp_1D( ...
    table_in_dd, ...
    table_axis_x_dd, ...
    table_out_dd, ...
    n_io, ...
    rwf_cal, ...
    rwf_io, ...
    plot_settings ...
    );


%% save data

% the idea for this section is borrowed from: 
%  - https://www.mathworks.com/matlabcentral/answers/84518

calibration_data.(table_AxisX_name) = cal.axis_x;
calibration_data.(table_out_A_name) = cal.axis_y_A;
calibration_data.(table_out_B_name) = cal.axis_y_B;
calibration_data.(table_out_C_name) = cal.axis_y_C;

io_data.(table_in_name) = io.table_in;
io_data.(switch_name) = io.switch;
io_data.(table_out_Value_name) = io.table_out;

save( ...
    strcat('./Data/', tc_name, '_Calibrations'), ...
    '-struct', ...
    'calibration_data', ...
    table_AxisX_name, ...
    table_out_A_name, ...
    table_out_B_name, ...
    table_out_C_name ...
    );

save( ...
    strcat('./Data/', tc_name, '_IO'), ...
    '-struct', ...
    'io_data', ...
    table_in_name, ...
    switch_name, ...
    table_out_Value_name ...
    );

end