% DD Data for random testing of ActiveReturnCdp TargetLink lookup tables.
classdef TC_DD_Data

    properties (Constant)
        
        pool = '/Pool'
        scalings = strcat(TC_DD_Data.pool, '/Scalings')
        types = strcat(TC_DD_Data.pool, '/Typedefs')
        AUTOSAR = strcat(TC_DD_Data.pool, '/Autosar')
        
        active_return = strcat( ...
            TC_DD_Data.AUTOSAR, ...
            '/Interfaces/Eps_Repository/ActiveReturn' ...
            )
        
        wApplI_AbsSteeringAngle_xdu16 = strcat( ...
                TC_DD_Data.active_return, ...
                '/ActiveReturnCdp/PortInterfaces/IProvideParameters/Operations/Get_mActRet_MaxMotorTorqueDepOnSteeringAngle_XAU16/OperationArguments/wApplI_AbsSteeringAngle_xdu16' ...
            )
        mActRet_MaxMotorTorqueDepOnSteeringAngle_XAU16_AxisX = strcat( ...
                TC_DD_Data.pool, ...
                '/Variables/ActiveReturnCdp/SHC/mActRet_MaxMotorTorqueDepOnSteeringAngle_XAU16_AxisX' ...
            )
        mActRet_MaxMotorTorqueDepOnSteeringAngle_XAU16_Value = strcat( ...
                TC_DD_Data.active_return, ...
                '/ActiveReturnCdp/PortInterfaces/IProvideParameters/Operations/Get_mActRet_MaxMotorTorqueDepOnSteeringAngle_XAU16/OperationArguments/mActRet_MaxMotorTorqueDepOnSteeringAngle_XAU16_Value' ...
                )

        vVehSpI_AbsMaxSafeVehSpd_xdu16 = strcat( ...
                TC_DD_Data.active_return, ...
                '/ActiveReturnCdp/PortInterfaces/IProvideParameters/Operations/Get_mActRet_MaxMotorTorqueDepOnVehSpeed_XAU16/OperationArguments/vVehSpI_AbsMaxSafeVehSpd_xdu16' ...
            )
        mActRet_MaxMotorTorqueDepOnVehSpeed_XAU16_AxisX = strcat( ...
                TC_DD_Data.pool, ...
                '/Variables/ActiveReturnCdp/SHC/mActRet_MaxMotorTorqueDepOnVehSpeed_XAU16_AxisX' ...
            )
        mActRet_MaxMotorTorqueDepOnVehSpeed_XAU16_Value = strcat( ...
                TC_DD_Data.active_return, ...
                '/ActiveReturnCdp/PortInterfaces/IProvideParameters/Operations/Get_mActRet_MaxMotorTorqueDepOnVehSpeed_XAU16/OperationArguments/mActRet_MaxMotorTorqueDepOnVehSpeed_XAU16_Value' ...
                )
            
        vVehSpI_AbsAvgVehSpd_xdu16 = strcat( ...
                TC_DD_Data.active_return, ...
                '/ActiveReturnCdp/PortInterfaces/IProvideParameters/Operations/Get_xActRet_MotorTorqueGain_XAU16/OperationArguments/vVehSpI_AbsAvgVehSpd_xdu16' ...
            )
        xActRet_MotorTorqueGain_XAU16_AxisX = strcat( ...
                TC_DD_Data.pool, ...
                '/Variables/ActiveReturnCdp/SHC/xActRet_MotorTorqueGain_XAU16_AxisX' ...
            )
        xActRet_MotorTorqueGain_XAU16_Value = strcat( ...
                TC_DD_Data.active_return, ...
                '/ActiveReturnCdp/PortInterfaces/IProvideParameters/Operations/Get_xActRet_MotorTorqueGain_XAU16/OperationArguments/xActRet_MotorTorqueGain_XAU16_Value' ...
                )

        mApplI_AbsDriverTorque_xdu16 = strcat( ...
                TC_DD_Data.active_return, ...
                '/ActiveReturnCdp/PortInterfaces/IProvideParameters/Operations/Get_xActRet_RetTorqueFactDepOnDriver_XAU16/OperationArguments/mApplI_AbsDriverTorque_xdu16' ...
            )
        xActRet_RetTorqueFactDepOnDriver_XAU16_AxisX = strcat( ...
                TC_DD_Data.pool, ...
                '/Variables/ActiveReturnCdp/SHC/xActRet_RetTorqueFactDepOnDriver_XAU16_AxisX' ...
            )
        xActRet_RetTorqueFactDepOnDriver_XAU16_Value = strcat( ...
                TC_DD_Data.active_return, ...
                '/ActiveReturnCdp/PortInterfaces/IProvideParameters/Operations/Get_xActRet_RetTorqueFactDepOnDriver_XAU16/OperationArguments/xActRet_RetTorqueFactDepOnDriver_XAU16_Value' ...
                )
            
        xActRet_SteerSpeedFactDepOnDriver_XAU16_AxisX = strcat( ...
                TC_DD_Data.pool, ...
                '/Variables/ActiveReturnCdp/SHC/xActRet_SteerSpeedFactDepOnDriver_XAU16_AxisX' ...
            )
        xActRet_SteerSpeedFactDepOnDriver_XAU16_Value = strcat( ...
                TC_DD_Data.active_return, ...
                '/ActiveReturnCdp/PortInterfaces/IProvideParameters/Operations/Get_xActRet_SteerSpeedFactDepOnDriver_XAU16/OperationArguments/xActRet_SteerSpeedFactDepOnDriver_XAU16_Value' ...
                )

        vActRet_NominalSteeringSpeed_XAU16_AxisX = strcat( ...
                TC_DD_Data.pool, ...
                '/Variables/ActiveReturnCdp/SHC/vActRet_NominalSteeringSpeed_XAU16_AxisX' ...
            )
        vActRet_NominalSteeringSpeed_XAU16_AxisY = strcat( ...
                TC_DD_Data.pool, ...
                '/Variables/ActiveReturnCdp/SHC/vActRet_NominalSteeringSpeed_XAU16_AxisY' ...
            )
        vActRet_NominalSteeringSpeed_XAU16_Value = strcat( ...
                TC_DD_Data.active_return, ...
                '/ActiveReturnCdp/PortInterfaces/IProvideParameters/Operations/Get_vActRet_NominalSteeringSpeed_XAU16/OperationArguments/vActRet_NominalSteeringSpeed_XAU16_Value' ...
                )

    end

    methods (Static)
        
        function out = dsdd_GetAll(str)
            out = dsdd('GetAll', str);
        end

        function out = get_wApplI_AbsSteeringAngle_xdu16_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.wApplI_AbsSteeringAngle_xdu16 ...
                );
        end

        function out = get_mActRet_MaxMotorTorqueDepOnSteeringAngle_XAU16_AxisX_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.mActRet_MaxMotorTorqueDepOnSteeringAngle_XAU16_AxisX ...
                );
        end

        function out = get_mActRet_MaxMotorTorqueDepOnSteeringAngle_XAU16_Value_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.mActRet_MaxMotorTorqueDepOnSteeringAngle_XAU16_Value ...
                );
        end
        
        
        function out = get_vVehSpI_AbsMaxSafeVehSpd_xdu16_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.vVehSpI_AbsMaxSafeVehSpd_xdu16 ...
                );
        end

        function out = get_mActRet_MaxMotorTorqueDepOnVehSpeed_XAU16_AxisX_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.mActRet_MaxMotorTorqueDepOnSteeringAngle_XAU16_AxisX ...
                );
        end

        function out = get_mActRet_MaxMotorTorqueDepOnVehSpeed_XAU16_Value_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.mActRet_MaxMotorTorqueDepOnSteeringAngle_XAU16_Value ...
                );
        end
        
        
        function out = get_vVehSpI_AbsAvgVehSpd_xdu16_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.vVehSpI_AbsAvgVehSpd_xdu16 ...
                );
        end

        function out = get_xActRet_MotorTorqueGain_XAU16_AxisX_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.xActRet_MotorTorqueGain_XAU16_AxisX ...
                );
        end

        function out = get_xActRet_MotorTorqueGain_XAU16_Value_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.xActRet_MotorTorqueGain_XAU16_Value ...
                );
        end
        
        
        function out = get_mApplI_AbsDriverTorque_xdu16_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.mApplI_AbsDriverTorque_xdu16 ...
                );
        end

        function out = get_xActRet_RetTorqueFactDepOnDriver_XAU16_AxisX_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.xActRet_RetTorqueFactDepOnDriver_XAU16_AxisX ...
                );
        end

        function out = get_xActRet_RetTorqueFactDepOnDriver_XAU16_Value_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.xActRet_RetTorqueFactDepOnDriver_XAU16_Value ...
                );
        end
        
        
        function out = get_xActRet_SteerSpeedFactDepOnDriver_XAU16_AxisX_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.xActRet_SteerSpeedFactDepOnDriver_XAU16_AxisX ...
                );
        end

        function out = get_xActRet_SteerSpeedFactDepOnDriver_XAU16_Value_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.xActRet_SteerSpeedFactDepOnDriver_XAU16_Value ...
                );
        end

        
        function out = get_vActRet_NominalSteeringSpeed_XAU16_AxisX_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.vActRet_NominalSteeringSpeed_XAU16_AxisX ...
                );
        end
        
        function out = get_vActRet_NominalSteeringSpeed_XAU16_AxisY_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.vActRet_NominalSteeringSpeed_XAU16_AxisY ...
                );
        end

        function out = get_vActRet_NominalSteeringSpeed_XAU16_Value_dd()
            out = TC_DD_Data.dsdd_GetAll( ...
                TC_DD_Data.vActRet_NominalSteeringSpeed_XAU16_Value ...
                );
        end
        
        function out = get_scaling(path)
           out = dsdd('GetAll', strcat(TC_DD_Data.scalings, '/', path));
        end
        
        function out = get_type(path)
           out = dsdd('GetAll', strcat(TC_DD_Data.types, '/', path));
        end

    end

end